### ISSUE TITLE
Bullet points

### ISSUE THREAD

**Issue by astoff** [minad/org-modern#10]
I think an en-dash `–` looks better than the box drawing character as a replacement for hypen-minus in `org-modern-list`.

**Comment by minad** [comment]
Or maybe not replace it at all?

**Comment by astoff** [comment]
Well, I guess you would still replace it by itself in that case, so
that a customization option remains in place.  But yes, hyphen-minus or
en-dash both look all right to me.

**Comment by minad** [comment]
Okay, I just checked. en-dash looks indeed better.

**Comment by minad** [comment]
Fixed in https://github.com/minad/org-modern/commit/4f5d010a9f862e622775d6977d0961b8682e8375
