### ISSUE TITLE
Change fringe when code block is collapsed

### ISSUE THREAD

**Issue by vedkothavade** [minad/org-modern#100]
When a code block is collapsed, the fringe glyph looks strange:
<img width="168" alt="Screen Shot 2022-11-17 at 6 26 31 PM" src="https://user-images.githubusercontent.com/60118973/202581392-308e3842-d2ca-46a3-81ee-85eb9e59365b.png">

Could this be changed, maybe to an arrow to indicate that it is collapsed, or just to a horizontal line without the right angle?

**Comment by minad** [comment]
Thanks for the suggestion. We currently don't monitor the folding state of blocks or headlines in Org, therefore we cannot support this easily. It would require additional intrusive changes and deeper hooking into Org mode. See the related issue #86 for headlines. If there is interest in this feature, I'd welcome a PR. But I haven't planned to implement this soon.

Anyway, I don't think it looks too strange. But well, that's a matter of taste of course. ;)
