### ISSUE TITLE
Copying tables to other files 

### ISSUE THREAD

**Issue by nicolas-graves** [minad/org-modern#101]
Hi!

When copying (yanking) tables from an org-mode file (with org-modern) to other files (e.g. a csv), I have trouble editing the file after it is copied (automated tabbing, kept formatting...). When closing the buffer and opening the file again, I can edit the file normally.

**Comment by minad** [comment]
You can save a raw string to the kill-ring using this command:

~~~ elisp
(defun +kill-ring-save-raw ()
  (interactive)
  (let ((filter-buffer-substring-function
         (lambda (beg end _delete)
           (buffer-substring-no-properties beg end))))
    (call-interactively #'kill-ring-save)))
~~~

With this command you won't copy the org-modern prettification.
