### ISSUE TITLE
org-beginning-of-line puts you at the end of the previous line

### ISSUE THREAD

**Issue by oantolin** [minad/org-modern#106]
Hi Daniel! I think I found a bug in org-modern. Steps to reproduce:

1. In `emacs -Q` (I'm on 28.2), run `M-x package-initialize`.
2. Create an org mode (I'm on version 9.5.5) file with the following contents:
```
* One
** TODO Two
```
3. Turn on `org-modern-mode`.
4. With point on `Two`, press `C-a`. It will take you to the end of the `* One` line. Pressing `C-f` puts you in between the two asterisks on the second line.

This wouldn't particularly bother me if it weren't for org speed keys, so I often do want to be on the very first character of the line.

**Comment by oantolin** [comment]
I bet it's using `display ""` that causes this, because I don't think I had this problem when I started using `org-modern`.

**Comment by oantolin** [comment]
Workaround:

```elisp
(defun disable-point-adjustment (&rest args)
  (setq disable-point-adjustment t))

(advice-add 'org-beginning-of-line :after #'disable-point-adjustment)
```

I'm not sure that's a feasible solution for `org-modern`, but I'm happy with it for my personal configuration.

**Comment by oantolin** [comment]
Maybe the best thing for now is to simply recommend this workaround. I mean, you can't use the new folding API unless you want to force users to upgrade Org; and that's probably a good idea eventually but not right away since 9.6 was just released.

**Comment by minad** [comment]
I think the invisible issue I've found with org-fold is only triggered by the local context in consult. If I use lineage or canonical instead, I may be able to revert to using invisible.

See https://github.com/minad/consult/blob/main/consult.el#L1348

**Comment by oantolin** [comment]
> I don't understand why display and invisible are handled differently with respect to point adjustments.

That is weird. It may be worth asking on the mailing list if that's on purpose.

**Comment by minad** [comment]
I already discussed a bit with @yantar92 about this. I have to figure out a better minimal example, but I believe there is a bug in org-fold-show-set-visibility and region folding restoration if the local context detail is used.

**Comment by abcdw** [comment]
It maybe related to this issue, but let me know if it should be reported separately.

org-modern 0.8

`(setq org-use-speed-commands t)`
`(org-modern-mode)`

I use `|` to demonstrate the position of the point.

```
* HH
** h1
** h2
|** h3
```
I press UU and get:
```
* HH
** h1
*U|* h3
** h2
```

I expect to get:
```
* HH
|** h3
** h1
** h2
```

**Comment by minad** [comment]
@abcdw I don't recall exactly, but moving upwards has always been broken. This seems to be a bug in Emacs anyway, in how it handles invisible text. We cannot do much about it.

**Comment by abcdw** [comment]
Moving downwards breaks the same way.

Another bug here:
`(setq org-use-speedkeys nil)`
`(org-modern-mode)`

```
|
** h
```

I press `C-n` `A` and get:

```

*A|* h
```

and another one:
```
|a
** h
```

I press `C-n` `C-a` and get:
```
a|
** h
```

**Comment by abcdw** [comment]
@minad As a workaround I set org-modern-hide-stars to nil for now  https://git.sr.ht/~abcdw/rde/commit/438950c

If we come up with a better solution, I'll drop a message.

BTW, thank you for working on the package! :)

**Comment by minad** [comment]
@abcdw Please try https://github.com/minad/org-modern/commit/29935ab99c07e03ac410bee3c7aa6c83afb2a9a9. Maybe we can switch the approach.

**Comment by abcdw** [comment]
@minad It seems all the cases mentioned above works correctly with 29935ab. So, it's probably a correct fix.

One more idea I had in mind as a potential fix, which I think can be a nice feature to have:

Instead of making leading stars invisible make them the same color as a background, it can be slightly confusing, but

1. It makes an outline structure clearer.
2. It makes it easier to directly edit underlying string.
3. It doesn't have any problems of invisible char interactions.


One more issue I found:
```
* a|
```
`M-right`:
![image](https://user-images.githubusercontent.com/1218615/223919449-883070dd-7a84-4e5a-bf85-27a24169bb0a.png)

but it should be:
![image](https://user-images.githubusercontent.com/1218615/223919507-718d24b5-2d2c-49bd-9567-d1d300a392ce.png)

After any input somewhere in the file it redisplays it correctly, so it's only a visual bug, no underlying stuff is broken.

**Comment by minad** [comment]
> Instead of making leading stars invisible make them the same color as a background, it can be slightly confusing,

That's already possible by setting org-modern-hide-stars to nil and setting org-hide-stars to t.

> One more issue I found

Yes, I already mentioned this in the commit message. Promotion/Demotion doesn't trigger refontify.

**Comment by abcdw** [comment]
> That's already possible by setting org-modern-hide-stars to nil and setting org-hide-stars to t.

@minad Cool, thank you for pointing it out!

> Yes, I mentioned this in the commit message. Promotion/Demotion doesn't trigger refontify. We could install hooks to fix this.

Yep, sorry, I skimmed commit message body too fast :)

If you could place 0.9 tag after fix incorporated, I would be glad to update org-modern guix package.

**Comment by abcdw** [comment]
Thank you!
Updated guix package: https://git.savannah.gnu.org/cgit/guix.git/commit/?id=201251b1ff
