### ISSUE TITLE
Possible to only use certain features?

### ISSUE THREAD

**Issue by jingxlim** [minad/org-modern#109]
Hi @minad, good work on the package -- org documents can be pretty too! I'm very much interested in using the package.

Is it possible to only use certain features of the package?

For example, I might want to disable any modifications to the table because there are [alignment issues](https://github.com/minad/org-modern/issues/5#issue-1148508330). Or perhaps I'm fine with how my `TODO` items  and `priority cookie` look, but would like to improve how my `tags` look.

Also, have you tested what happens when used in `doom-emacs`? I understand `doom-emacs` already made some stylistic adjustments out-of-the-box. Do they conflict?

Finally, I cannot write `emacs-lisp` so pardon me if these are some questions I can look into myself if I read the code. Thanks and looking forward to your response!

**Comment by minad** [comment]
See https://github.com/minad/org-modern#introduction

**Comment by jingxlim** [comment]
Thanks for your response. I hope you don't mind me responding in this closed issue.

I did read the Introduction before coming here. From my reading of the Introduction, I understood that what I am after was not possible (and hence this thread). There's only a single "switch" -- `org-modern-mode` -- that is either ON/OFF; and customization was not possible.

You did write ...
> You can use SVG tags and use the table and block styling from `org-modern`.

... but did not provide an example of how to do that.

Currently, I would like to enable all stylistic changes but disable the ones related to `TODO`, `priority cookies` and `tables` because I already made my own customizations to those. If it is not too much work, could you tell me how to achieve this?

Many thanks!

**Comment by minad** [comment]
The introduction:

> This package implements a “modern” style for your Org buffers using font locking and text properties. The package styles headlines, keywords, tables and source blocks. The styling is configurable, you can enable, disable or modify the style of each syntax element individually via the org-modern customization group.
