### ISSUE TITLE
Changing org priority symbols

### ISSUE THREAD

**Issue by dschaehi** [minad/org-modern#110]
First of all, thanks a lot for the `org-modern` package! My `org-mode` experience has improved much after using this package. 
One feature I miss though is the possibility to change org priority symbols (e.g., replace `[#A]` with `‼️` and `[#B]` with `❗️`). There is an existing package called [`org-fancy-priority`](https://github.com/harrybournis/org-fancy-priorities), which does precisely the job but slows down loading .org files when run together with `org-modern`. I wonder if there is an easy way to integrate `org-fancy-priority` into `org-modern`.

**Comment by minad** [comment]
Thanks. Currently changing priority symbols is not supported. But I
would welcome a PR which adds support. The feature could be easily
implemented in a similar way as the replacement feature of
org-modern-keyword, which was contribued by @tecosaur.

**Comment by dschaehi** [comment]
Thanks for the tip (I guess you are referring to this pull request #51)!
I am however not so versed in Emacs Lisp. Perhaps someone else who shares the same need can do this?

**Comment by minad** [comment]
@dschaehi Yes, one could basically copy the way this was in implemented in #55.

**Comment by dschaehi** [comment]
Awesome, thanks @minad ! There is one minor issue though. The changes are not rendered correctly in org agenda. I wonder whether this is due to my Doom Emacs setup or a general issue.

**Comment by minad** [comment]
Please try https://github.com/minad/org-modern/commit/3d029bd32aca2117dbabb9e71a968f39acdac4a3.

**Comment by dschaehi** [comment]
Thanks. The symbols are correctly shown but the priority colors set by `org-priority-faces` are not correctly shown (below is my setting in Doom Emacs). Can you confirm this in your setup?
```lisp
(setq org-priority-faces
        '((?A . error)
          (?B . warning)
          (?C . success)))
```

**Comment by minad** [comment]
Yes, you have to set the colors manually for the strings in the `org-modern-priority` alist using `propertize`. This is by design.

**Comment by dschaehi** [comment]
Based on your suggestion I put the following in the init file to mimic `org-priority-faces`, but this does not seem to change the colors of the priorities in org agenda. I wonder whether I use `propertize` correctly below:
```lisp
(setq org-modern-priority
          '((?A . (propertize "‼" 'face 'error))
            (?B . (propertize "!" 'face 'warning))
            (?C . (propertize "-" 'face 'sucess))))
```

**Comment by minad** [comment]
See https://www.gnu.org/software/emacs/manual/html_node/elisp/Quoting.html and https://www.gnu.org/software/emacs/manual/html_node/elisp/Backquote.html

**Comment by dschaehi** [comment]
Many thanks for the references! The following worked.
```list
    (setq org-modern-priority
          `((?A . ,(propertize "‼" 'face 'error))
            (?B . ,(propertize "!" 'face 'warning))
            (?C . ,(propertize "-" 'face 'sucess))))
```
--
“If you give a man a fish, you feed him for a day. If you teach a man to fish, you feed him for a lifetime.”
