### ISSUE TITLE
Recommended setup for `org-modern` with variable pitch

### ISSUE THREAD

**Issue by zmberber** [minad/org-modern#111]
I like to have `org-mode` in `variable-pitch-mode`.  I then change all of the relevant faces, like `org-code`, `org-block`, and `org-table` to inherit `fixed-pitch`.

But then, the tables don't look right with `org-modern`.

![2023-01-15_16-32](https://user-images.githubusercontent.com/29400525/212550322-148e63d7-4406-4337-b56d-f439b74fef41.png)

What is the recommended setup for `org-modern` with variable pitch?

**Comment by minad** [comment]
No official recommendation but you can disable prettification individually via org-modern-* customization variables.

**Comment by zmberber** [comment]
yes, disabling that is my current setup.

but there should be a way to make it work, right?  that is what i am asking about.

**Comment by minad** [comment]
See #5
