### ISSUE TITLE
`org-modern-keyword` didn't modify `title` keyword

### ISSUE THREAD

**Issue by rezaamashi** [minad/org-modern#115]
Hi, Thanks for the amazing package

I have an doom emacs set up and set `org-modern-keyword` to 
```emacs-lisp
(use-package!
    :custom
   (org-modern-keyword 
      '((t . t)
        ("title" . "") ;; to hide the keyword and only show the content
        ("subtitle" . "") 
        ("macro" . "Ⓜ")    
        ;; and more  
       )))
```
This only hide the `#+subtitle:` keyword but not `#+title:`. Consult the attached images below. Although I increase the size of the `org-document-title` face (Attachment 1). I also tried it in a lean, non-doom, environment with this [init.el](https://0x0.st/HzYD.txt) (Attachment 2). but the problem persists. Lastly, I also tried to change set `title`keyword to `("title" . "T")` or anything else but the problem persists. 
Thanks 

Attachment 1 - with my Doom setup
![Screenshot-2023030585649](https://user-images.githubusercontent.com/20262272/222937493-dc94f324-a0a2-4266-b444-66d32cf57444.png)

Attachment 2 - with a lean sandbox environment
![Screenshot-2023030585652](https://user-images.githubusercontent.com/20262272/222937520-cb7d9e1d-b148-441d-a86e-6bff2dc9d8ff.png)

**Comment by minad** [comment]
There seems to be a typo in your init.el. "title " instead of "title".

**Comment by rezaamashi** [comment]
> There seems to be a typo in your init.el. "title " instead of "title".

Hi, I forget to check back on this issue. 
Yes, it is. The typo is the culprit. 
Thank you.
