### ISSUE TITLE
mention org-modern-indent

### ISSUE THREAD

**Issue by jdtsmith** [minad/org-modern#117]
> Note that org-indent-mode interferes with some of the style elements applied by  org-modern-mode, e.g., the block brackets in the fringe

You might mention org-modern-indent here, which is now more stable as it no longer uses dirty font-searching hacks (in fact I borrowed some of the ideas from your fringe block font-lock code).

**Comment by minad** [comment]
Yes, I may mention it but it doesn't seem ready yet. Does it work with line-spacing>0? Do you plan to release it on ELPA/MELPA? Ideally I would also add this to org-modern itself but it is very complex, which I find hard to justify for the block prettification only.

**Comment by jdtsmith** [comment]
> Does it work with line-spacing>0?

I mean it works but just doesn't look as good.  

![image](https://user-images.githubusercontent.com/93749/225314179-b9434d26-e27e-42d3-958c-7e6ae9b6dff7.png)

Unless I'm missing something (possible), by definition you cannot draw within the line-space pixel buffer between lines.  It is documented at least.   I would recommend people use a _font_ with larger line spacing.

> I would also add this to org-modern itself

Would be better long term.  I actually had the latest rewritten version as a draft PR for you, but then once I looked at the complexity (which grew when I discovered editing headings re-indents the contents), thought better of it.  There was great response on Reddit, so it seems people are interested in this functionality.

> Do you plan to release it on ELPA/MELPA?

I may let it simmer for a bit longer with the (completely rewritten) new version and then submit it to Elpa.  Not sure it belongs there, though.  Lots of people are using :straight now it seems.

**Comment by minad** [comment]
> ...doesn't look as good.

This is what I mean. It does not work.

> Unless I'm missing something (possible), by definition you cannot draw within the line-space pixel buffer between lines. It is documented at least. I would recommend people use a font with larger line spacing.

I disagree. `line-spacing` is a perfectly good setting. I implemented org-modern with line-spacing>0 in mind. I believe there is a possible solution. You can maybe create a thin white space character (display space width 1) and then give it the color of the line as background. This way you should get a continuous line. The rounded corners are a bigger problem though.

> There was great response on Reddit, so it seems people are interested in this functionality.

Yes, it seems that there is interested, so I am not opposed to adding it. But it must work with line-spacing>0.

> I may let it simmer for a bit longer with the (completely rewritten) new version and then submit it to Elpa. Not sure it belongs there, though. Lots of people are using :straight now it seems.

Okay, maybe rather add it to org-modern directly.

**Comment by jdtsmith** [comment]
> line-spacing is a perfectly good setting

As is org-indent ;). 

> I believe there is a possible solution. You can maybe create a thin white space character (display space width 1) and then give it the color of the line as background. This way you should get a continuous line.

Interesting idea. I didn't realize you can style the full-height background like this (never used line-space>1).  It would actually be good to stop including the bracket in the line-prefix when the block is flush-left, since when editing headings, org-indent aggressively re-prefixes the entire content (which means I have to aggressively re-style the indent).

I played around with specified space with BG a bit:

- background gets overwritten by selected region, hl-line, etc. overlays.  Looks strange to have your brackets "disappear" when selected.
- I really wish there were a `display :before` option for text-properties; how do you handle this?  It's awkward when block content is flush-left to the beginning of the line.  Do you copy the first character of the line as propertied string, prepend the slim bracket glyph and display-replace it as a decorated version of itself?  Need a `:before`!  If I figure this out, and I can simplify the current design of org-modern-indent so as not to worry anymore about what org-indent is doing with the indent.
- For the curved bit on the begin/end line, I haven't found a really satisfactory solution.
- Unicode box chars work fine in terminal, pixel-width spaces do not (but also line-spacing=1 is enforced in terminal).
- Haven't figured out how to draw the "curved ends".  I could do a "fade to black" series of thin spaces as an alternative.

So maybe a solution would look like:

- terminal: just use box-chars as normal (ideally with the :before-like approach if I can find it). 
- gui with line-indent=1: same
- gui with line-indent>1: use thin specified spaces with color BG, and either no bar ends or a "fade to BG" style.

Seems like a simpler solution is out there (sans SVG of course).  I also note that many modes draw with unicode box characters (vundo, various tree-modes, etc.) will also break with line-spacing>1.  One may sensibly argue these types of modes have "standalone control" of their buffer so can enforce line-space=1.  But still, it's not a unique problem.

> Okay, maybe rather add it to org-modern directly.

That would be my preference too.   I'll noodle with it.

**Comment by minad** [comment]
Note that terminal support is not very relevant for org-modern. org-modern only aims to work well on the GUI due to its visual features. I never tested this package in the terminal. Some prettifications may work well nevertheless.

**Comment by jdtsmith** [comment]
Something like these are possible, independent of line-spacing:

![image](https://user-images.githubusercontent.com/93749/225439091-095c1f20-31e2-42ec-864d-f7f81ab0e961.png) ![image](https://user-images.githubusercontent.com/93749/225439433-9daddf2c-fe0e-4298-80b7-529b5452d66f.png)  ![image](https://user-images.githubusercontent.com/93749/225441271-2a59c06c-86e0-474d-895f-d4f366020103.png) ![image](https://user-images.githubusercontent.com/93749/225442034-6da396cf-0a3d-4b4b-8122-13b5d8503059.png)

But selecting still them overrides the BG value, as does the cursor.

**Comment by jdtsmith** [comment]
One could also I suppose use overlays. Then `before-string` would be possible. Sounds difficult to keep track of though.
