### ISSUE TITLE
Unexpected leading stars with Modus and EF themes

### ISSUE THREAD

**Issue by KaranAhlawat** [minad/org-modern#118]
If I use Org Modern mode with an ef-themes theme, or a modus theme, then I get the following result

![image](https://user-images.githubusercontent.com/56113511/225826609-3ab5cd11-e9ac-4d82-895a-308ac7c924df.png)

But the same problem does not persist with a doom-theme or the default theme, for example.
![image](https://user-images.githubusercontent.com/56113511/225827705-c4e5557f-53f9-4b0f-a1be-01c26ead393c.png)

Settings I think may be relevant (would be glad to share if other information is required):
1. org-modern-mode is set to t.
2. org-indent-mode is set to t.
3. org-modern-indent-mode can be set to t or nil, the problem persists.
4. org-modern-hide-stars is set to 'leading or nil.
5. org-hide-leading-stars is set t
6. org-indent-mode-turns-on-hiding-stars is set to nil.

**Comment by minad** [comment]
Thanks for the report. I cannot reproduce this issue, so it may be caused by some details of your configuration. Please share a minimal recipe which demonstrates the issue, starting from emacs -Q only loading Modus, Ef and Org-modern.

**Comment by KaranAhlawat** [comment]
Fair enough, after more digging it even happens with org-superstar, so not an org-modern issue. Thank you for your time.
