### ISSUE TITLE
"End of Buffer" Moving to Next Line from Heading

### ISSUE THREAD

**Issue by dstrr** [minad/org-modern#119]
If point is at the beginning of a heading, that is at the left-most star, then moving down a line with `C-n` triggers an "End of Buffer" error when attempting to move down to an sub-heading in some cases. I cannot replicate this behavior in all cases. 

There is another case which is consistent for me. 
```
* DONE Heading
:LOGBOOK:
- State "TODO"       from              [2023-03-18 Sat 21:44]
:END:
```
Moving point to beginning of line `:LOGBOOK:` and then moving down to the line `- State ...` and then once again attempting to move down will trigger "End of Buffer" and move point to the end of `:LOGBOOK:` line. 

Any idea what might be causing this?

**Comment by minad** [comment]
I cannot reproduce this. This issue is likely not caused by org-modern. Can you create a minimal recipe starting from emacs -Q?

**Comment by dstrr** [comment]
Thanks for the quick response! I dug around and found that setting `bidi-display-reording` to `nil` is what causes this. The docs state that setting it to `nil` is unsupported, so I've set it to`'left-to-right` instead. This seems to have fixed the issue.
