### ISSUE TITLE
org-modern-priority: Use different characters by default? (NEGATIVE CIRCLED LATIN CAPITAL LETTERS are not widely supported)

### ISSUE THREAD

**Issue by Keks-Dose** [minad/org-modern#12]
The variable Org Modern Priority prints garbage, maybe because my machine lacks a necessary fonts, but which?

C-h v org-modern-priority, customize:

`Hide Org Modern Priority:`

`Alist:`

`INS DEL Character: A
            String: 🅐`

`INS DEL Character: B
            String: 🅑`

`INS DEL Character: C
            String: 🅒`

`INS`

`    State : STANDARD.
   List of priority label replacements. Hide
   Set to nil to disable styling priorities.
Groups: Org Modern`

I've seen that your example uses letters in a circle for priorities, but how to get them?

**Comment by minad** [comment]
Your **default font** lacks support for these characters. Currently I use Iosevka which supports these characters. While there exist plenty of programming fonts I am not aware of a list of fonts which have comprehensive coverage. I also tried Hack and Source Code Pro and neither of those two fonts supports these characters. So maybe I should change the defaults. You can also set `org-modern-priority=nil` to disable this feature entirely or use different characters.

**Comment by andersjohansson** [comment]
Emacs by default falls backs to Symbola if that is installed. I reinstalled it and that worked, but for me caused a slight problem with differing line heights compared to my default font...
