### ISSUE TITLE
Propertize custom priorities strings

### ISSUE THREAD

**Issue by ckoshikumo** [minad/org-modern#121]
When customizing the display of priorities, for example:

`(setq org-modern-priority '((?A . "!!!") (?B . "!!") (?C . "!")))`

it doesn't seem to be possible to also customize the faces. This doesn't work:

`(setq org-modern-priority-faces '((?A :foreground "red")))`

Neither does this:

`(setq org-modern-priority-faces '(("!!!" :foreground "red")))`

Is there something I'm missing? If not, I'd like to suggest this as an enhancement. Thanks!

**Comment by minad** [comment]
You can propertize the strings of org-modern-priority directly.
