### ISSUE TITLE
next-line doesn't work when point between two asterisks

### ISSUE THREAD

**Issue by abcdw** [minad/org-modern#123]
Initial setup: `(setq org-modern-hide-stars nil)`, `(org-modern-mode)`.

`|` - is a position of point.

```org
*|* Heading
body
```
When I press `C-n` (`next-line`), it doesn't move the cursor and says `next-line: End of buffer`, even if it clearly not the end of the buffer.

It happens only with the second level heading.

**Comment by abcdw** [comment]
There is a chance that it caused by something else, but it's very small, I orginally did everything with:

`emacs -Q`
`(require 'org-modern)`

and tried it one more time today. The org-modern version is 0.9.

**Comment by minad** [comment]
I don't see this. I use an Emacs from just a few days ago, also with emacs -Q of course.

**Comment by abcdw** [comment]
```
guix shell --pure -E '.*GTK.*|.*XDG.*|.*DISPLAY.*|SHELL' emacs-next-pgtk emacs-org-modern -- emacs -Q
```
emacs version is 30.0.50-0.ac7ec87.

```
(progn
  (require 'org-modern)
  (setq org-modern-hide-stars nil)
  (org-mode)
  (org-modern-mode))

** Heading
content
```

Ok, I launched it in as clean environment as possible, still reproduces. I can try to build a latest emacs, but later.

**Comment by minad** [comment]
Maybe it is a pgtk problem? Anyway there is probably nothing we could do. Org-modern does the *right thing* now with 715a8280dcddfa00cf422231c1d4e5aa1ee87753. If the stars are not hidden Org-modern only adds a display property to the last star, nothing else. Emacs should handle that correctly.

**Comment by abcdw** [comment]
Not a pgtk problem, tried on `emacs-next-tree-sitter`, but on `emacs` (which is emacs 28) it works correctly. So, will try to check it later on newer emacs version.

**Comment by minad** [comment]
Interesting. I hope there is no regression in the newer display code. If you find something, the Emacs maintainers are probably interested in a report, as long as you can create a self-contained recipe without Org.
