### ISSUE TITLE
Last Update not Installing on Spacemacs

### ISSUE THREAD

**Issue by nicolasshu** [minad/org-modern#125]
Hmmm... 
The last update is not allowing Spacemacs to install org-modern on Spacemacs via `dotspacemacs-additional-packages`. That feature on Spacemacs still works for every other  package, but not `org-modern`, so I always have to go through `M-x package-install` to install `org-modern`.  Do you know why this would happen?

**Comment by minad** [comment]
I am not familiar with the Spacemacs installation routine. I suggest you ask the Spacemacs developers. Thanks!

**Comment by nicolasshu** [comment]
No worries. I figured I would ask. Thanks!

**Comment by nicolasshu** [comment]
https://github.com/syl20bnr/spacemacs/issues/15980
