### ISSUE TITLE
Some characters only show Unicode encoding in variable-pitch mode

### ISSUE THREAD

**Issue by langshangyuan** [minad/org-modern#127]
Some characters show normally if I use the global default font to a mono-space font. But when I activate the `variable-pitch-mode` there are some characters only show the Unicode encoding, like the `+U2611`, and `+U2733` and the checkbox symbol.

**Comment by minad** [comment]
This means that you use a font which doesn't support these characters. I recommend the Iosevka font collection for monospaced fonts and DejaVu Sans for variable pitch.

**Comment by langshangyuan** [comment]
But I change the face attribute of the `org-modern-symbol`, there is no clear effect.

**Comment by langshangyuan** [comment]
I also input these characters into other Editor, they works well.

**Comment by langshangyuan** [comment]
I test the font on a Linux environment, all characters work well, but on Windows machine, these characters don't work, do I need some extra configurations or not.

**Comment by dragove** [comment]
I've encountered the same problem and it can be solved by installing `synmbola` font. Hope this can help you, too.
