### ISSUE TITLE
Org-modern blocks subtree movement/refiling

### ISSUE THREAD

**Issue by japhir** [minad/org-modern#128]
Since a while I get some issues with org-modern!

Here are the steps to recreate what I did: use [alphapapa's with-emacs](https://github.com/alphapapa/with-emacs.sh/)

```sh
with-emacs.sh -i org-modern
```

create a new org file, e.g. ~/Downloads/test-org-modern.org, write:
```org
* test
** heading
*** inheritance
* new
```

M-x org-modern-mode

This gives me the following warning:
```
Warning (comp): org-modern.el:807:27: Warning: the function ‘pos-bol’ is not known to be defined. Disable showing Disable logging
```

Now to get the real issues:
1. Put cursor on heading test and use M-S-left arrow or right arrow to try to move an org-heading down a level, including its children
    -> Only the current heading moves.
2. Navigate cursor to heading new, C-c C-w to refile it, type test.
    -> The heading gets copied to test, but remains its own heading as well

Turn off org-modern-mode and try again to get the desired behaviour.

org-modern.el has this in it:
```elisp
;; Created: 2022
;; Version: 0.9
;; Package-Version: 20230422.634
;; Package-Commit: e0a1a00490acc3bbbf199e433c9ef60e03f9d416
```

**Comment by minad** [comment]
You probably use Straight, which doesn't respect dependencies, see https://github.com/radian-software/straight.el/issues/1083. Ensure that you update all packages.

**Comment by japhir** [comment]
Hey thanks for getting back to me.

I do have compat installed however! I've used use-package with :ensure t to install org-modern, which should take care of dependencies. I had also just done a M-x list-packages (... wait for refresh) U y.

> Status: Installed in ‘compat-29.1.4.1/’.
> Version: 29.1.4.1

In my list of packages it says it's been installed as a dependency.
> Required by: with-editor-20230212.2214, transient-20230508.1924, org-modern-20230422.634, moody-20230212.2015, magit-section-20230428.1518, magit-20230502.1321, keycast-20230212.2016, git-commit-20230313.1724

But to prevent it being an issue with my own setup, I included the MWE that uses with-emacs.sh to show that it also occurs when I only install org-modern (and its dependencies) (which just uses `(package-install X)`). 

Cheers

**Comment by minad** [comment]
I don't know what the issue is, but I cannot reproduce it with emacs -Q and org-modern and compat. Maybe you use a very outdated commit of Emacs 29?

**Comment by japhir** [comment]
I'm on Emacs 29.0.50, which I've built quite a while ago because compilation takes so long. This might be the issue?

**Comment by japhir** [comment]
You were right, updating to Emacs 30.0.50 has resolved this issue! Thanks :)

**Comment by minad** [comment]
Please make sure that you update Emacs more regularly if you use the master branch to prevent such issues in the future. The master branch cannot be considered stable since it is early in its life cycle. Otherwise I recommend that you use Emacs 29 from the emacs-29 branch which is stable. Personally I compile Emacs from the emacs-29 branch myself until Emacs 30 stabilizes a bit more.
