### ISSUE TITLE
Org bullets don't show when org-modern-mode is active.

### ISSUE THREAD

**Issue by apoorv569** [minad/org-modern#129]
I am using the `org-superstar-mode` to have nice bullets instead of `*` and it worked fine with `org-modern-mode` until recently it stopped working. Now after the first level heading none of the further bullets show.

![2023-05-10_01-54](https://github.com/minad/org-modern/assets/53279454/a89de3ec-dac0-45fc-bfc8-65a7fef511c2)

Disabling `org-modern-mode` fixes the issue and the bullets are visible again.

![2023-05-10_01-56](https://github.com/minad/org-modern/assets/53279454/d4810821-fe85-4fcc-9545-84c070e71cfa)

**Comment by minad** [comment]
Org-modern replaces Org-superstar. Org-modern also prettifies the bullets/stars by default.

**Comment by apoorv569** [comment]
> Org-modern replaces Org-superstar. Org-modern also prettifies the bullets/stars by default. Just install and enable one of the two packages, but not both.

I removed `org-superstar` but I still have to disable then re-enable `org-modern-mode` before I can see the bullets again.

**Comment by jumper047** [comment]
I'm not sure is it separate issue or not - have same issue as topic starter, but doesn't have org-super-star installed. Also noticed that stars appears if I disable `org-indent-mode`

**Comment by apoorv569** [comment]
> I'm not sure is it separate issue or not - have same issue as topic starter, but doesn't have org-super-star installed. Also noticed that stars appears if I disable `org-indent-mode`

Hmm.. I just disabled `org-indent-mode` and bullets appear, re-enabling it hides the bullets again.

This is weird, I think the issue is `org` itself?

So either toggling  `org-modern-mode` and `org-indent-mode` can fix the bullets not appearing.

**Comment by minad** [comment]
@apoorv569 I am not aware that org-indent-mode makes problems for org-modern-stars. org-indent-mode is only incompatible with the block prettification, but there is @jdtsmith's [org-modern-indent](https://github.com/jdtsmith/org-modern-indent) for that. Can you create a minimal recipe starting from emacs -Q which shows the issue with the stars?

**Comment by minad** [comment]
I tested org-indent-mode again and it indeed leads to problems due to a recent change. I pushed a fix (https://github.com/minad/org-modern/commit/cced7f7db43c9e8f4d925278e7bff307d6e26480). Please check if it works for you.

**Comment by apoorv569** [comment]
> I tested org-indent-mode again and it indeed leads to problems due to a recent change. I pushed a fix ([cced7f7](https://github.com/minad/org-modern/commit/cced7f7db43c9e8f4d925278e7bff307d6e26480)). Please check if it works for you.

It seems to be working now.

Also thanks for the `org-modern-indent` package recommendation.

**Comment by jumper047** [comment]
Just installed update and can confirm that it fixes the issue for me
