### ISSUE TITLE
Share theme and frame/font configuration in README

### ISSUE THREAD

**Issue by DivineDominion** [minad/org-modern#13]
The example GIF looks to beautiful to be true  :) When I turn on `org-modern-mode`, I don't get as nice source block highlights and my variable pitch font doesn't play as nicely with the "pills" for TODO states and dates etc.

@minad Could you share the relevant config to replicate your GIF's look in an additional `.el` file or in the README?

**Comment by minad** [comment]
For now I leave this as an exercise for the Emacs fiddler. But as mentioned in the README, the theme is Modus Operandi with some tweaks of the Modus customization options. :smile:

**Comment by minad** [comment]
That's odd. How does it look for you? Did you try emacs -Q with modus-operandi enabled only?

**Comment by fintelkai** [comment]
I'll fiddle and explore when I have time. If I figure out what my problem is, I'll update. I just recently returned to using doom, so some of what's going on is more opaque to me than when I was using my own handmade config.

**Comment by minad** [comment]
Oh okay. Maybe Doom will also consider this package at some point? But @tecosaur told me that Doom is already applying heavy adjustments (or maybe that was only his config), which makes it hard to include something like org-modern which is opinionated itself. I think Doom at least uses org-indent-mode by default and this mode doesn't play too well with org-modern-mode, see also #7.

**Comment by tecosaur** [comment]
If org-modern is (as I hope/expect it is) fairly modular and extensible (i.e. changing/removing/adding prettifications), performs well, and can doesn't mess with other things Dooom/I have going on, I'll likely advocate for its inclusion in Doom.

**Comment by minad** [comment]
Yes, it is sufficiently modular. You can enable/disable elements one by one and it tries to go out of the way. However a bigger problem is that some of the styles applied here are incompatible with other modes like org-indent-mode and there is no good solution in sight for that since the source blocks use the fringe and the fringe is obviously not indented. So one should either use one mode or the other.

**Comment by DivineDominion** [comment]
@fintelkai I was missing the nice source block borders, too -- turns out you need to enable non 0 width fringes! 

But mine are grey by default, so that's what prompted me personally to request minimal reproducible style settings

**Comment by DivineDominion** [comment]
Thanks for the addition @minad
