### ISSUE TITLE
Enhance customization possibilities for modern-label-border

### ISSUE THREAD

**Issue by publicimageltd** [minad/org-modern#130]
First of all, thanks for this great package! 

I had troubles customizing the face `org-modern-label`. I set it in `use-package` and was surprised that it had no effect on startup. I found out that this face is further changed in `org-modern--update-label-face`, where the optional `:box` attribute is being added. That's nice, but my use case is that I want this face with a smaller border.. The built-in calculation doesn't work.  So I'm stuck with either using a face with no `:box` at all, or the default border.

My suggestion is to enhance `org-modern-label-border` to allow for an explicit face symbol as a further argument. So its either `t` or nil, in which case the current code runs; or `facep`, in which case this value is used instead of `org-modern-label`. Alternatively, it could be a list which is passed to `:box` directly (instead of calculating the border). Actually, the latter seems to be cleaner. What do you think?

**Comment by minad** [comment]
Thanks. Did you notice that you can set org-modern-label-border to an integer. This should work for your use case if you want to reduce the border width. I don't think we need additional configuration choices. If possible the auto computation should be improved to also handle your scenario.
