### ISSUE TITLE
[Feature request] Compatibility with org-appear

### ISSUE THREAD

**Issue by dschaehi** [minad/org-modern#131]
[org-appear](https://github.com/awth13/org-appear) makes invisible parts of Org elements appear visible. 
I think this feature is very helpful when editing time stamps, properties and so on.
Would it be possible to make org-modern compatible with org-appear?

![Demo](https://github.com/awth13/org-appear/blob/master/demo.gif?raw=true)

**Comment by minad** [comment]
See https://github.com/awth13/org-appear/issues/47
