### ISSUE TITLE
A vertical line on the left side of the #+begin_src blocks is gone

### ISSUE THREAD

**Issue by refaelsh** [minad/org-modern#132]
The vertical line on the left side of the #+begin_src blocks is gone, like can be seen in the README gif, is not there for me. Here is the relevant part of my config:
```
(add-hook 'org-mode-hook 'org-indent-mode)
    (use-package org-modern)
    (with-eval-after-load 'org (global-org-modern-mode))
    (setq org-src-preserve-indentation nil
          org-src-tab-acts-natively t
          org-hide-emphasis-markers t
          org-ellipsis "…"
          org-catch-invisible-edits 'show-and-error
          org-pretty-entities t
          org-edit-src-content-indentation 2
          org-agenda-tags-column 0
          org-agenda-block-separator ?─
          org-agenda-time-grid
            '((daily today require-timed)
            (800 1000 1200 1400 1600 1800 2000)
            " ┄┄┄┄┄ " "┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄")
          org-agenda-current-time-string
            "⭠ now ─────────────────────────────────────────────────")
```

Please help :-)

**Comment by minad** [comment]
I don't observe a problem in my setup or with emacs -Q. Please start with emacs -Q and try each of the settings independently to determine which setting causes the issue.

**Comment by refaelsh** [comment]
Understood. I will do it right now.

**Comment by refaelsh** [comment]
I tried it with the following minimal config:
```
(require 'package)
(setq package-archives '(("melpa" . "https://melpa.org/packages/")
                         ("org" . "https://orgmode.org/elpa/")
                         ("elpa" . "https://elpa.gnu.org/packages/")))
(package-initialize)
(unless package-archive-contents
  (package-refresh-contents))

(unless (package-installed-p 'use-package)
  (package-install 'use-package))
(require 'use-package)
(setq use-package-always-ensure t)


(add-hook 'org-mode-hook 'org-indent-mode)
(use-package org-modern)
(with-eval-after-load 'org (global-org-modern-mode))
```

The problem still occurs,

**Comment by minad** [comment]
I don't see the issue on Emacs 28 or 29. Which Emacs version do you use? Maybe your Emacs installation has some issue, see for example https://github.com/minad/org-modern/issues/113? Just to make sure - these lines are only visible in GUI Emacs and not on the terminal.

**Comment by refaelsh** [comment]
> Which Emacs version do you use?

28.2

> Maybe your Emacs installation has some issue

Maybe, but it is out of my hands, I just used my distro's package manager. I use NixOS.

The latest that is available on NixOS is 28.2 - that is what I use.

> Just to make sure - these lines are only visible in GUI Emacs and not on the terminal.

Yes, I do run it in GUI mode.

**Comment by minad** [comment]
Maybe you use org-indent-mode? I saw that in your snippet above. If org-indent-mode is used the fringe lines are disabled.

**Comment by refaelsh** [comment]
> It seems you use org-indent-mode. If org-indent-mode is used the fringe lines are disabled. This is intentional.

Hmm... Ok, I removed it from the minimal config and the problem went away.
Then I removed it from my full config, and to my big surprise, the problem is still there.

**Comment by refaelsh** [comment]
> You can also try https://github.com/jdtsmith/org-modern-indent in addition to org-modern.

Interesting. Thank you for the suggestion. I will check it out.
