### ISSUE TITLE
Prettify +filetags tag?

### ISSUE THREAD

**Issue by tiejunhu** [minad/org-modern#135]
Hi, thank for this briliant package.

I have a question about the org-modern-tag option. When it's enabled, is it possible to render the head line tags after the +filetags keyword?

**Comment by minad** [comment]
Styling filetags is currently not possible, since it is a special case independent of the usual tag styling. But I would welcome a patch which adds this.

**Comment by tiejunhu** [comment]
I made it work by adding another keyword font lock to it, will you accept a PR by adding keywork font lock?

```
(use-package org-modern
  :after org
  :hook
  (org-modern-mode .
                   (lambda ()
                     (font-lock-add-keywords
                      nil
                      '(("^#\\+filetags:\\( \\)\\(:\\(?:[[:alnum:]_@#%]+:\\)+\\)[ 	]*$" (0 (org-modern--tag)))
                        ("^#\\+FILETAGS:\\( \\)\\(:\\(?:[[:alnum:]_@#%]+:\\)+\\)[ 	]*$" (0 (org-modern--tag))))
                      t))))

```

**Comment by minad** [comment]
Yes, you can add this to the org modern font lock keywords. Please reuse org-tag-re.
