### ISSUE TITLE
Indentation of org blocks

### ISSUE THREAD

**Issue by walseb** [minad/org-modern#137]
Hello!

It appears that when you prettify org src blocks, their indentation gets hidden. 

And so a block that's at the start of the line looks identical to one that's indented. This hides any mistakes where you accidentally indent a block, and makes undo history more confusing.

Is there an option to stop the indentation from being hidden?

Thanks!

**Comment by minad** [comment]
There is no option for that. Indenting blocks (or anything) in Org is not a great idea in my opinion. The particular problem here is to prettify indented blocks nicely. That's not trivial since the lines around the block are only displayed in the fringe.

**Comment by walseb** [comment]
Hi!

I agree, it's not a great idea to indent src blocks. My issue is primarily being able to see my mistake if I do it accidentally.

I suppose a simpler solution would be to define font lock rules that highlight src blocks with indentation using a warning font.

Thanks for considering!

**Comment by nick4f42** [comment]
> My issue is primarily being able to see my mistake if I do it accidentally.

I use indented source blocks in list items, so it's important to me as well.

Indenting the block name to the same indentation as the `#+` seems like a good enough solution. It doesn't look particularly good, but the alternative is not knowing the indentation. For example:

```
 fringe
/ column 1
|/
:1
:
:- without org-modern
:
:  #+begin_example
:foo
:  #+end_example
:
:- current org-modern behavior (unable to determine indentation)
:
|example
|foo
|example
:
:- proposed behavior
:
|  example
|foo
|  example
:

```
