### ISSUE TITLE
All-the-icons svg support

### ISSUE THREAD

**Issue by Stebalien** [minad/org-modern#139]
It would be nice to be able to replace keywords/block names with icons. This "just worked" when `all-the-icons` used fonts/faces, but it won't when the `svg` branch is merged as it will put an image in the display property and emacs doesn't recursively render display properties (i.e., it won't apply the display property of a string in a display property).

I'm happy to submit a patch to address this but figured I should open an issue to discuss it first.

My [current solution](https://github.com/minad/org-modern/compare/main...Stebalien:org-modern:steb/all-the-icons-support?expand=1) is to:

1. Detect strings that consist only of the "￼" (object replacement) character.
2. Use said character's display property.

This allows configurations like:

```elisp
(setopt org-modern-keyword
    `(("name" . ,(all-the-icons-material-icons "label"))))
```

Without directly depending on `all-the-icons`.

I've also considered two alternatives:

1. Direct `all-the-icons` support.
2. Arbitrary display property lists.

**Direct `all-the-icons` support**

Allow icons to be specified directly. Unfortunately, this would require depending on `all-the-icons` directly which is likely out of scope for this project.

```elisp
(setopt org-modern-keyword
    `(("name" . (material-icons "label"))))
```

**Arbitrary display property lists** 

Allow specifying arbitrary display properties, in addition to strings:

```elisp
(setopt org-modern-keyword
    '(("name" . (image ...))))
```

This is the most general purpose solution but it's _slightly_ more annoying to use with `all-the-icons`:

```elisp
(setopt org-modern-keyword
    `(("name" . ,(get-text-property 0 'display (all-the-icons-material-icons "label")))))
```

Additionally, this option doesn't conflict with my current approach which detects the "￼" character so it may be reasonable to support both methods.

**Comment by minad** [comment]
Hi, thanks for the proposal. I am okay with supporting lists in addition to strings as replacement. It seems this just needs a relaxation of the rep predicate. As you point out, configuration will be slightly inconvenient, but this can be easily mitigated by a simple custom helper function. At least we avoid direct dependency on icon libraries and on the object replacement character implementation detail. Feel free to open a PR. Thanks!
