### ISSUE TITLE
TODO and TAG character not at center when fontsize is changed

### ISSUE THREAD

**Issue by Fmajor** [minad/org-modern#140]
I try to set different font-size for different org-level, e.g. like below
```
  (dolist
      (face
       '((org-level-1 1.7 "#81a2be" ultra-bold)
         (org-level-2 1.6 "#b294bb" extra-bold)
         (org-level-3 1.5 "#b5bd68" bold)
         (org-level-4 1.4 "#e6c547" semi-bold)
         (org-level-5 1.3 "#cc6666" normal)
         (org-level-6 1.2 "#70c0ba" normal)
         (org-level-7 1.1 "#b77ee0" normal)
         (org-level-8 1.0 "#9ec400" normal)))
```
Then i find that the font size of  `TODO`, `priority`, `timestamp` and `tags` are unchanged and their background color height become larger and the font do not center in the background, which is kind of ugly. How can we handle this?
 
![image](https://github.com/minad/org-modern/assets/1620897/44503126-73cc-4da7-bc87-048fc1254db2)

**Comment by minad** [comment]
The vertical alignment of the labels depends on your font and sizes. We don't have a way to adjust the alignment. I recommend to avoid font sizes which differ so much. Furthermore you can try different fonts, which are better balanced. I use the Iosevka set of fonts.

**Comment by Stebalien** [comment]
Is it not possible to use the raise display property for this?

**Comment by minad** [comment]
@Stebalien Indeed, that could work.
