### ISSUE TITLE
how to set org-modern-horizontal-rule attribute

### ISSUE THREAD

**Issue by ST-Saint** [minad/org-modern#145]
I use a dark theme and the org horizontal line is invisible. I tried the following config but it doesn't change the face.

```elisp
(set-face-attribute 'org-modern-horizontal-rule nil :foreground "white" :strike-through "white" :bold 't :inherit nil)
```

Is there anything I did wrong? What is the right way to modify it? 

Thanks

**Comment by minad** [comment]
The horizontal rule should work without configuration. Please try the modus-vivendi theme with emacs -Q to check if it works. Maybe you are affected by #83 (Mac issue)?

**Comment by ST-Saint** [comment]
It turns out that doom-theme messes it up
solved by https://github.com/minad/org-modern/issues/59

**Comment by fleimgruber** [comment]
@ST-Saint which comment in #59 exactly solved it for you?
