### ISSUE TITLE
org-modern overrides line-prefix settings from other packages

### ISSUE THREAD

**Issue by ahmed-shariff** [minad/org-modern#148]
This is a followup from https://github.com/nobiot/org-transclusion/issues/201

org-transclusion modifies the fringe by setting the `line-prefix` and `warp-prefix`. org-modern is overwriting this by setting them nil.

As I mentioned in the issue referenced, I don't fully understand fortifying in emacs, I am not sure where it would need to be addressed. Looking at the code, here is also it may not be trivial to change that behavior.

**Comment by minad** [comment]
You can set org-modern-block-fringe=nil to disable this.

**Comment by ahmed-shariff** [comment]
Apologies for the slow reply. I thought that had solved the issue, but this still seems to persist. The `org-modern--unfontify` is also effecting the `line-prefix` and `warp-prefix` but is not controlled by `org-modern-block-fringe` ?

**Comment by minad** [comment]
@ahmed-shariff Thanks, you are right. Fixed.

**Comment by ahmed-shariff** [comment]
Dang that was quick 😍🥳
Thank you! :)
