### ISSUE TITLE
Keep a little org heading indentation

### ISSUE THREAD

**Issue by stardiviner** [minad/org-modern#15]
I suggest to keep a little indentation space before org heading stars.

```elisp
(defun org-modern--star ()
  "Prettify headline stars."
  (let ((level (- (match-end 1) (match-beginning 1))))
    (put-text-property
     (match-beginning 2)
     (match-end 2)
     'display
     (concat (make-string level ?\ )
             (aref org-modern-star (min (1- (length org-modern-star)) level))))))
```

Here is it looks like:

<img width="1183" alt="image" src="https://user-images.githubusercontent.com/378699/156279594-aa62d163-370e-4270-ae5e-4f5a10003c5e.png">

**Comment by minad** [comment]
Did you check out `org-modern-hide-stars`? You can set it to nil.

https://github.com/minad/org-modern/blob/074b7e5b514a0d7758bc0afce3d107ddc40c5da2/org-modern.el#L73-L78

**Comment by stardiviner** [comment]
But this will leave the leading stars appearing. I wish it can be empty before the icon. Is there a way to archive this style?

**Comment by minad** [comment]
Sure, also set `org-hide-leading-stars=nil`.
