### ISSUE TITLE
set "org-special-ctrl-a/e" to "t" does not work when "org-modern-hide-stars" is "t"

### ISSUE THREAD

**Issue by zhenhua-wang** [minad/org-modern#152]
When `org-modern-hide-stars` is `t`, C-a will always bring the cursor before the stars regardless of the value of `org-special-ctrl-a/e`.

**Comment by minad** [comment]
There have been multiple similar issues where the stars affected speed keys or C-a handling. These issues cannot be fixed in org-modern, which only adds styling but doesn't override commands.
