### ISSUE TITLE
Missalign in org-clock-report

### ISSUE THREAD

**Issue by lucashdez** [minad/org-modern#156]
Hello, first of all, sorry for the english spelling mistakes, i'm not native.
I don't know if this issue has been already covered, but i've found that if you get the org-clock-report and add the timestamp column it missaligns the output table:
![image](https://github.com/minad/org-modern/assets/60920384/6c923067-f38d-4a1f-a1d7-0519ff92ef4f)
Is there any way to solve it? 
Thanks in advance.

**Comment by minad** [comment]
Duplicate #5
