### ISSUE TITLE
Obvious differentiation of keywords

### ISSUE THREAD

**Issue by pradyparanjpe** [minad/org-modern#157]
### Suggestion

Change rendering/style of `#+keywords` to differentiate them from plain text.

### Use-case
This may display my dumbness,
but it took me quite some time to recognise that
one of my inclusions `#+INCLUDE: "myfile.org"` was in fact written (pasted from somewhere) as `INCLUDE: "myfile.org"`

Now, expecting `org-modern` to have stripped the `#+`, I kept wondering why `myfile` doesn't get exported.

### Better elsewhere
I really like how tags such as the one in `* HEADING    :noexport:` get rendered. Why not extend something similar to keywords?

**Comment by minad** [comment]
See the docstring of org-modern-keyword.

**Comment by pradyparanjpe** [comment]
Sorry, my bad...
