### ISSUE TITLE
Todo tags in agenda view

### ISSUE THREAD

**Issue by AndreasMatthias** [minad/org-modern#158]
Todo tags are not displayed correctly in all agenda views.

Tested with versions:

* org: 9.6.12 
* org-modern: 20230905.806

Start emacs with `emacs -Q` and evaluate the following:

```emacs-lisp
(package-initialize)

(use-package org
  :bind (("s-o a" . #'org-agenda)))
(add-to-list 'org-agenda-files "~/Notes/agenda/agenda.org")

(use-package org-modern
  :config (global-org-modern-mode))
```

Todo tags in the agenda are displayed incorrectly when viewing both agenda and todo list together (key: `s-o a n`). The face is `org-todo` instead of `org-modern-todo`.

![an](https://github.com/minad/org-modern/assets/1072202/6660683c-a7f4-4664-98f7-bd2b6569b584)

Note that the face is correct, i.e. `org-modern-todo`, in agenda view (key: `s-o a a`) as well as in todo list view (key: `s-o a t`).

![aa](https://github.com/minad/org-modern/assets/1072202/5ddab514-9bff-465e-8768-451b3782dafd)
![at](https://github.com/minad/org-modern/assets/1072202/6b1e1597-6f22-4a40-b0ae-bf9077b2d958)

**Comment by minad** [comment]
Duplicate #26. This is an old Org bug, the variable `org-todo-keywords-for-agenda` is not initialized properly.

**Comment by minad** [comment]
Thanks. Good to know. Please Report this upstream on the Org mailing list.

**Comment by AndreasMatthias** [comment]
I've just checked out the most recent `main` branch of Org (`commit 57b94f3447b9046dac2f9238e24ad902510056cc`) and todo tags are displayed correctly for my reported test case. Hurray!
