### ISSUE TITLE
Intereferes with org-beginning-of-line

### ISSUE THREAD

**Issue by astoff** [minad/org-modern#16]
With point on a heading, if I type `C-a` then point jumps to the end of the previous line, so one character further than it should.

**Comment by minad** [comment]
You can set `org-special-ctrl-a/e=t` to mitigate the issue - you may want to consider this setting unrelated to this issue. When I use the normal command `beginning-of-line` command it doesn't jump beyond the current current line. Therefore I think this an issue in `org-beginning-of-line`. I looked briefly at the function, but nothing stood out as the culprit. It could be that the first `beginning-of-line` moves just to the visible star and after that, the point is moved inside the hidden stars. As soon as the window is redisplayed, the cursor is then moved away from the invisible region by the display engine, unfortunately in the wrong direction.

**Comment by dears1rr** [comment]
I have the same problem, using beginning-of-visual-line. This is an example, when I use C-a on the second line:
`#+TITLE: test
#+author: test`

**Comment by minad** [comment]
Indeed, I see this too now. The issue is that I tried the commands via M-x and there everything works. This means this is indeed broken for all the movement commands.

**Comment by astoff** [comment]
Excellent, work fine now! For the record, the previous version also broke the "speed keys" functionality because it was impossible to place point at bol (it ended up between two asterisks, somehow).
