### ISSUE TITLE
Question on your org mode config

### ISSUE THREAD

**Issue by dears1rr** [minad/org-modern#17]
I have a little question that has little to do with the package:
In your gif example, there is a character that is at the beggining and end of the content of the buffer:
![pic](https://user-images.githubusercontent.com/100808426/156469499-14c450f9-bd39-4a7f-b417-35b0035f7e6e.png)

What package or piece of code do you use for that? It looks cool, I would be happy to add that to me config.

**Comment by minad** [comment]
This is `indicate-buffer-boundaries=t`. I have that enabled in text and prog buffers.

**Comment by dears1rr** [comment]
Thank you!
