### ISSUE TITLE
COMMENT keyword not being prettified

### ISSUE THREAD

**Issue by LemonBreezes** [minad/org-modern#179]
Hi. The `COMMENT` keyword just gets the `org-special-keyword` face and no prettification from this package. :(

**Comment by minad** [comment]
I don't see this, `#+comment: ...` gets prettified correctly on my side.

**Comment by LemonBreezes** [comment]
> I don't see this, `#+comment: ...` gets prettified correctly on my side. Can you reproduce this in a minimal setup starting from emacs -Q?

Nonono, I meant like this
![image](https://github.com/minad/org-modern/assets/29102529/7ebf515a-f8af-44f8-abbe-c60271ea3daa)

**Comment by minad** [comment]
Okay, I see. You would like to have a style similar to dates or TODO keywods? I don't think we need a special style for this one, but I am not opposed to adding this if someone propose a good PR. Are there other such special headline keywords we could support?

Generally please take more care when creating issues or feature requests, since I cannot understand what you mean otherwise.

**Comment by minad** [comment]
@LemonBreezes Btw, I usually use the `:noexport:` tag if I want to prevent exporting some headlines. Do you know if COMMENT offers any advantages over using such a tag?

**Comment by LemonBreezes** [comment]
> @LemonBreezes Btw, I usually use the `:noexport:` tag if I want to prevent exporting some headlines. Do you know if `COMMENT` offers any advantages over using such a tag?

I don't know to be honest. It seems purely aesthetic, though I never knew about `:noexport:`. I just basically spent the hours preparing this bug report for Org mode https://lists.gnu.org/archive/html/emacs-orgmode/2024-03/msg00037.html so that I can get the special keywords and dates to not overwrite the heading backgrounds:
![image](https://github.com/minad/org-modern/assets/29102529/4d365711-f9b0-47a0-8fa6-13457adf5519)
![image](https://github.com/minad/org-modern/assets/29102529/d09e3900-6ab6-4528-a4d5-f161cd047630)

Sorry for not being detailed, it's basically just me being lazy.

**Comment by minad** [comment]
> I don't know to be honest. It seems purely aesthetic, though I never knew about :noexport:.

For me the advantage of `:noexport:` is that it reuses tags. It doesn't seem justified to introduce special syntax only for this. Therefore I also don't see the need to add special support here.

> Sorry for not being detailed in the issues, it's basically just me being lazy.

Please take it into account for the future. This helps avoiding some back and forth.
