### ISSUE TITLE
checkboxes only work for 1st level headings

### ISSUE THREAD

**Issue by shroomist** [minad/org-modern#181]
I'm using checkbox strings `[ ]` as my todo keywords.
`org-modern-checkbox` seems to also catch those in headings but only for the first level headings.
would have been cool to have it being supported on all heading levels.

<img width="408" alt="Screenshot 2024-03-16 at 22 18 03" src="https://github.com/minad/org-modern/assets/95058/138906d5-ccd5-464b-811d-2004a68a0077">

**Comment by minad** [comment]
This is actually a bug in Org. `org-list-full-item-re` recognizes check boxes for first level headings, since ` * [ ] item` is valid list syntax. Note that space before the star!
