### ISSUE TITLE
How to increase the size of timestamps and tags?

### ISSUE THREAD

**Issue by maikol-solis** [minad/org-modern#19]
Hi! 

I have this config in doom

```
(setq doom-font (font-spec :family "Hack" :size 13)
      doom-variable-pitch-font (font-spec :family "Roboto" :size 13)
      doom-unicode-font (font-spec :family "Hack")
      doom-big-font (font-spec :family "Hack"))
```
When I load `org-modern` all the timestamps and tags look extremely small which is hard to see. 

![image](https://user-images.githubusercontent.com/4078489/156694232-a30343e7-4138-40aa-b79b-1091a0a7dd0c.png)

This is the normal state for comparison
![image](https://user-images.githubusercontent.com/4078489/156694446-7db4213b-8cf6-4ae3-8d46-801214fd7a81.png)

How could I increase the font size in the “modernized” parts?

Thanks.

**Comment by protesilaos** [comment]
Try something like this:

```elisp
(set-face-attribute 'org-modern-label nil :height 0.9)
```

**Comment by minad** [comment]
I increased the font size by default. However in my setup I still have the issue that headline labels look good if you use increased headline sizes, but dates look very compressed.

**Comment by protesilaos** [comment]
> I increased the font size by default. However in my setup I still have
> the issue that headline labels look good if you use increased headline
> sizes, but dates look very compressed.

@minad I find that the metrics of fonts do not grow linearly.  You are
using standard Iosevka, right?  Check these:

```elisp
;; line length stays the same, but height changes
(set-face-attribute 'default nil :family "Iosevka" :height 80)
(set-face-attribute 'default nil :family "Iosevka" :height 90)

;; line length changes
(set-face-attribute 'default nil :family "Iosevka" :height 90)
(set-face-attribute 'default nil :family "Iosevka" :height 100)
```

Same for all fonts.

In addition, some fonts retain their width/height but adjust the shape
of the glyphs.  For example:

```elisp
;; same metrics but larger glyphs for the 105
(set-face-attribute 'default nil :family "Hack" :height 100)
(set-face-attribute 'default nil :family "Hack" :height 105)
```

So your problem may be because of this.

**Comment by minad** [comment]
No, I think the problem is that the labels/tags use a fixed :box line-width, which looks good if the line height is larger than the default line height. By compressed I didn't mean the characters but the box around the text. There is not enough padding, so it looks compressed.

**Comment by maikol-solis** [comment]
Reviewing the properties  of `org-modern-label` I changed the `width` to `normal` and I got this in doom

```
(custom-set-faces!
  '(org-modern-label :width normal)
  '(org-modern-time-active :inherit nano-strong-i))

```
![image](https://user-images.githubusercontent.com/4078489/156884586-4021b05c-4c27-44a6-bb3f-4c646415a2f5.png)

It looks much better.
