### ISSUE TITLE
Top 2 level default fold glyphs not support by many fonts

### ISSUE THREAD

**Issue by jdtsmith** [minad/org-modern#192]
Very nice new fold capability.  Unfortunately the top two levels of the new `'fold` characters don't seem to be supported in many fonts, e.g. [Iosevka](https://typeof.net/Iosevka/specimen).  E.g. 0x2B9E BLACK RIGHTWARDS EQUILATERAL ARROWHEAD isn't present in any fonts on my system.   

Unfortunately there are far more right-facing than down-facing arrows.  A couple possibilities include `("˃" . "˅") ("↦" .  "↧")`; there may be more.

**Comment by lassemaatta** [comment]
Excellent, I was just googling what might cause this :)

Btw, I think the 4th level symbols are in the wrong order (`("▿" . "▹")`), I assume they should be similar to the three other pairs (right + down, not down + right)?

**Comment by jdtsmith** [comment]
[This site](https://www.fileformat.info/info/unicode/char/2b9f/fontsupport.htm) catalogs which fonts support which characters, i.e. not many for the nice looking ['BLACK DOWNWARDS EQUILATERAL ARROWHEAD' (U+2B9F)](https://www.fileformat.info/info/unicode/char/2b9f/index.htm).

**Comment by minad** [comment]
Thanks. Tbh I found the equilateral arrowhead even a little bit too fancy. I use triangles only now which looks more neutral and work better with Iosevka (and probably many other fonts). I noticed that the equilateral arrowhead came from some separate FreeSerif font on my system which also caused inconsistencies with the monospaced Iosekva in my setup.

**Comment by jdtsmith** [comment]
The new 2nd level triangles (aka "BLACK MEDIUM DOWN/RIGHT-POINTING TRIANGLE") are [not available in many fonts](https://www.fileformat.info/info/unicode/char/23f5/fontsupport.htm), so display code will very often reach for another font, which often changes the line spacing (and slows redisplay).

I suggest switching to [0x25B8, `▸`](https://www.fileformat.info/info/unicode/char/25b8/fontsupport.htm) and [0x25BE, `▾`](https://www.fileformat.info/info/unicode/char/25be/fontsupport.htm)

**Comment by minad** [comment]
I've updated the list in https://github.com/minad/org-modern/commit/5393edbb5a078348d0eea5723868c35be3e73494. I use https://www.fileformat.info/info/unicode/char/2bc8/index.htm now. All the triangles are at least supported by Iosevka and Pragmata.

**Comment by minad** [comment]
Btw, the README suggests to use a separate face for org-modern'ized symbols. This should avoid display issues.

~~~
(set-face-attribute 'org-modern-symbol nil :family "Iosevka")
~~~

Besides that, the list is customizable.

**Comment by jdtsmith** [comment]
Sadly no medium triangles in my fonts.  Will customize.  I don't know how many people know a missing glyph will "pull up" another font automatically, which means line spacing can change for lines with that glyph.

**Comment by minad** [comment]
Which font do you use?
