### ISSUE TITLE
New folding indicators do not render well in doom Emacs

### ISSUE THREAD

**Issue by maikol-solis** [minad/org-modern#193]
Hi! 

After this commit, https://github.com/minad/org-modern/commit/bcb5f81f478fd69709a9832fd7d25dcb16352cab I noticed the new folding indicators aren't rendering properly in doom Emacs. 

![image](https://github.com/minad/org-modern/assets/4078489/6421a9ed-e65d-4b90-ac0a-72a9441bde6a)

Doom uses Nerd Font icons, and maybe I should use them too to ensure everything works.

I'm just checking to make sure it's not something else. 

Best.

**Comment by minad** [comment]
Duplicate #192

**Comment by maikol-solis** [comment]
After your last commit, everything works perfect. Very nice feature btw. 

![image](https://github.com/minad/org-modern/assets/4078489/1e40ca58-7159-4cb8-aef8-2b7a983a3215)
