### ISSUE TITLE
org-modern-tag-faces does not work as expected

### ISSUE THREAD

**Issue by dinkonin** [minad/org-modern#197]
Hi, thanks for the new `org-modern-tag-faces`  feature.
while testing I notice that the doctstring proposes this format:
```emacs-lisp
 (setq org-modern-tag-faces
    (quote (("work" :background "red" :foreground "yellow"))))
```
this does not work for me until I change "work" to "**:**work**:**",

Also it does not work for multiple tags i.e.  :project1:task1:work:

**Comment by minad** [comment]
I believe this has been fixed already.
