### ISSUE TITLE
Opt-out for fold indicators?

### ISSUE THREAD

**Issue by port19x** [minad/org-modern#198]
I noticed that org-modern now uses fold indicators instead of the unicode bullets it did before, as recently added as a feature.
After checking the related PR and code, it is not apparent to me how I could reproduce the prior behaviour without downgrading my version.
Am I missing something?
Is this intentional to lower maintenance burden?
I think a customization option to get the old behaviour would be nice, but I can also live with the alternative of pinning v1.2

**Comment by minad** [comment]
Of course the old style is still available. You can set `org-modern-star=replace` to go back to the old style.
