### ISSUE TITLE
fold-stars doesn't work well when org-cycle twice on header

### ISSUE THREAD

**Issue by zhenhua-wang** [minad/org-modern#203]
Thank you all for making this feature available! I found this bug when calling `org-cycle' twice on header, which means unfold all subheaders. The indicators of subheader do not changed to unfold status.

![2024-05-19 13-49-14](https://github.com/minad/org-modern/assets/11971417/4c615ed9-7204-4a08-8363-0a226a94546d)

**Comment by minad** [comment]
Duplicate of https://github.com/minad/org-modern/discussions/195. Unfortunately I cannot reproduce this problem.
