### ISSUE TITLE
Wrong bullet character

### ISSUE THREAD

**Issue by Hixer05** [minad/org-modern#212]
Org-modern uses the wrong character for bullets, a triangular one:

![2024-06-09-231135_hyprshot](https://github.com/minad/org-modern/assets/60942163/fa39db6c-29ec-4cbe-92a8-df4ff0ef394b)

### Info:
```
Nixos-24.05
Emacs 29.3
```
### To replicate:
- Open vanilla emacs (no config)
- `package-install` org-modern
- Open .org file
- `M-x org-modern-mode`

**Comment by minad** [comment]
No, it is all correct like this. See the option `org-modern-star`.
