### ISSUE TITLE
Issue with additional components of deadline date display 

### ISSUE THREAD

**Issue by fintelkai** [minad/org-modern#22]
Org datestamps can include components that control when an item appears on the agenda, such as `DEADLINE: <2022-03-07 Mon -0d>` (which says that the item should not appear until the very day it's due). `org-modern` seems to get tripped up by such things. At least, the display doesn't treat that component the way I would have expected (probably just with one styling for the entire datestamp). See screenshot.

<img width="287" alt="Screen Shot 2022-03-05 at 08 25 25" src="https://user-images.githubusercontent.com/3893496/156885094-856321a9-72a1-4e38-9076-c984693f7b51.png">

**Comment by protesilaos** [comment]
Hello @fintelkai!  This is intentional.  Check this for another example:

```
<2022-03-05 Sat 16:05>
```

`org-modern` distinguishes between active and inactive timestamps.  Compare these:

```
[2022-03-05 Sat 16:05]
<2022-03-05 Sat 16:05>
```

**Comment by fintelkai** [comment]
Hmm, ok. I find it weird to have the auxiliary component look more highlighted than the main time info. Is part of it the interaction with modus-operandi?

**Comment by protesilaos** [comment]
> Is part of it the interaction with modus-operandi?

No.  The faces are defined in `org-modern`.

As for the main VS auxiliary, let's wait for the maintainer.

**Comment by minad** [comment]
The reason for the current look is that the auxiliary component occurs behind the time and uses the same color as the time. We could handle the case separately where no time is specified.

**Comment by fintelkai** [comment]
Nice. Thanks!
