### ISSUE TITLE
static-if not available in emacs 29.4

### ISSUE THREAD

**Issue by tohammer** [minad/org-modern#220]
static-if is used in newest main since
https://github.com/minad/org-modern/commit/bf2cec740dcf41fe8b4cc1ecc537c4fc4c7e9403

but results in this error in 29.4:
redisplay--pre-redisplay-functions: (invalid-function static-if)

Looks like it was only added for emacs 30, maybe follow the suggestion from comment
https://github.com/emacs-mirror/emacs/blob/a952ca5461c590fe194a2f96622603d6ccaebb47/lisp/subr.el#L279

**Comment by minad** [comment]
static-if is provided by Compat 30. Make sure to update both Compat and Marginalia.
