### ISSUE TITLE
New invalid-function error with static-if  

### ISSUE THREAD

**Issue by christianromney** [minad/org-modern#221]
Unsure why [this isn't working](https://github.com/christianromney/dotfiles/blob/main/private_dot_config/doom/config.org#modern-appearance) for me any more, but I noticed the last commit introduced `static-if`. 

My `*Messages*` buffer contains the following errors:

```
File mode specification error: (invalid-function static-if)
redisplay--pre-redisplay-functions: (invalid-function static-if) [112 times]
```

Oddly enough eval'ing `org-modern--update-label-face()` in a buffer works fine. Any pointers would be much appreciated. 

```shell
$ doom version

GNU Emacs     v29.4            nil
Doom core     v3.0.0-pre       HEAD -> master 0b135252 2024-07-10 04:22:48 -0400
Doom modules  v24.08.0-pre     HEAD -> master 0b135252 2024-07-10 04:22:48 -0400
```

**Comment by christianromney** [comment]
I just now noticed the prior commit requires Emacs 30 for compatibility. Perhaps this is it. If so, please accept my apology for the noise. I will try that, update here, and close this issue if it works.

**Comment by minad** [comment]
Duplicate #220.

**Comment by christianromney** [comment]
Sorry for the noise. Confirmed working on 30.
