### ISSUE TITLE
Triggers (invalid-function static-if) constantly

### ISSUE THREAD

**Issue by Schievel1** [minad/org-modern#222]
If org-modern-mode it active for the current buffer and point is in this buffer, it shows 
`redisplay--pre-redisplay-functions: (invalid-function static-if) [136 times]`
in the minibuffer. With the times value counting up. 

I do not know if this is really a problem of org-modern or if it is normal with my very new version of emacs that this macro is missing. But if it's the latter you probably want to know either. 

I am using emacs 29.3.50

**Comment by Schievel1** [comment]
Ok, I think Doom Emacs' version of compat was just a little too old. 
13 hours ago Hendrik pushed a commit that bumps compat. So a simple `doom upgrade` helped here.

**Comment by minad** [comment]
I wonder - is Doom still using Straight? I hope they upgrade to Elpaca soon, which will catch such dependency problems with warnings. Note that when you install packages from Git, dependencies must still be respected. Org-modern from the main branch requires Compat version 30.

**Comment by Schievel1** [comment]
Correct, they still use straight.
