### ISSUE TITLE
Change to compat v30 breaks installation on debian systems

### ISSUE THREAD

**Issue by DirkSchmitt** [minad/org-modern#223]
The change to compat v30 is IMHO to early. 
The version was released only 4 days ago and is not landed in mainstream distributions e.g. Debian including sid.
See: https://tracker.debian.org/pkg/compat-el

Please postpone this change to avoid dependency conflicts.

**Comment by minad** [comment]
I don't recommend to use mixed installations, where some packages come from the system package manager and others come from ELPA/MELPA. But in any case, you can install the stable version 1.3 of org-modern, which doesn't rely on the newest Compat version.
