### ISSUE TITLE
end_src with no newline formats incorrectly

### ISSUE THREAD

**Issue by gitrj95** [minad/org-modern#23]
<img width="604" alt="image" src="https://user-images.githubusercontent.com/68976909/156930287-7a1c39f9-294c-46ad-a818-bc41796ae20f.png">

this is an awesome package. thanks for your work (generally, not just here)

**Comment by minad** [comment]
I cannot reproduce this. Please try emacs -Q and paste the exact org text you used.

**Comment by minad** [comment]
Closing due to lack of response. If you give me a precise recipe on emacs -Q to reproduce this I can try to fix any potential issues. In any case, if you get invalid font locking it may help to turn org-modern-mode off and on again.
