### ISSUE TITLE
Missing Unicode characters "⯈" and "⯆" in many fonts

### ISSUE THREAD

**Issue by lazzalazza** [minad/org-modern#232]
I've encountered an issue with the use of the Unicode characters "⯈" (U+2BC8) and "⯆" (U+2BC6) in `org-modern-fold-stars`. These characters appear to be missing from many common fonts, causing unexpected behavior when rendering folded elements in my Org-mode files.

Here is my current workaround, where I replaced "⯈" and "⯆" with other Unicode characters that are more widely supported:

```
(setq org-modern-fold-stars
      '(("▶" . "▼")
        ("▷" . "▽")
        ;; ("⯈" . "⯆")
        ("▷" . "▽")
        ("▹" . "▿")
        ("▸" . "▾"))
)

```
Workaround: As shown in the code above, I have commented out the line using "⯈" and "⯆" and replaced them with alternatives which seem to be supported by the fonts I commonly use (eg. "Source Code Pro").

Request: It would be helpful to have a more robust way to handle missing Unicode characters or improved documentation on fonts that support these specific symbols.

Thanks for your attention!

**Comment by minad** [comment]
Duplicate #224
