### ISSUE TITLE
table gets misaligned when item has progress cookie

### ISSUE THREAD

**Issue by igorcafe** [minad/org-modern#239]
To reproduce:

1. Use the default config in README
2. Copy this org:

```org
* Clocks
#+BEGIN: clocktable :scope file :maxlevel 2
#+END:

* Tasks

** TODO clock 1 [1/10]
CLOCK: [2024-10-23 qua 12:37]--[2024-10-23 qua 14:42] =>  2:05

** TODO clock 2 [1/2]
CLOCK: [2024-10-23 qua 12:37]--[2024-10-23 qua 14:42] =>  2:05
```

3. press `C-c C-c` over `#+BEGIN:` to generate clock report
4. you should reproduce the misalignment

![image](https://github.com/user-attachments/assets/267ec1a3-1b28-4496-bbf4-d012a83bf9ef)

**Comment by minad** [comment]
Dup #5
