### ISSUE TITLE
Pixel Perfect Alignment on roadmap?

### ISSUE THREAD

**Issue by ParetoOptimalDev** [minad/org-modern#24]
In [the System Crafters video about your packages](https://www.youtube.com/watch?v=f0FMo_XxujU) you mentioned *maybe* implementing pixel perfect alignment. I was curious so I came here to search for an issue and found you mentioned it in #5, but there's no issue for it alone.

So I'm creating this issue to ask for myself and any future interested parties. It's fine if the answer is "no, this is wayyy to difficult and not worth it", thanks for this awesome package.

aside: I was trying to create something similar using the nano icons that came out and I stopped because of how much of a pain handling all the cases were, so I very much appreciate such a simple package that improves QoL so much :smile:

**Comment by minad** [comment]
Yes, it is planned but not high priority. We can continue the discussion in #5. 

Duplicate #5, #11
