### ISSUE TITLE
Breaks org-agenda-tags-column set to auto

### ISSUE THREAD

**Issue by kpzart** [minad/org-modern#241]
When I activate org-modern-mode and have `org-agenda-tags-column` set to `auto`, the tags will be misplaced by a few columns to the left, so they flow at of the screen. I guess this is due to the additional whitespace chars that come with `org-modern`

![image](https://github.com/user-attachments/assets/57b33a4b-7f03-4ab9-8086-8b4ac19c5674)

![image](https://github.com/user-attachments/assets/426c8267-788a-42ab-b4bf-ddf7260b88c2)

I am on emacs 29.4 with spacemacs.

**Comment by minad** [comment]
Duplicate #207. This setting is not supported.
