### ISSUE TITLE
org-modern-agenda does not find all keywords in custom agenda views

### ISSUE THREAD

**Issue by protesilaos** [minad/org-modern#26]
Hello Daniel!

On my end (Emacs 29) the `org-modern-agenda` does not work as intended
for entries in the `org-agenda-custom-commands`.  You can try it with
the default `C-c a n` sequence (agenda and all TODOs).

The problem is that the `org-done-keywords-for-agenda` and
`org-todo-keywords-for-agenda` are not set properly.  For my custom
views, both remain nil.  For `C-c a n` only the `org-done-keywords`
captures the relevant words.

**Comment by minad** [comment]
Thanks for the report. It seems that the variable `org-done-keywords-for-agenda` is always set properly. Only `org-todo-keywords-for-agenda` is not initializd for `C-c a n`. I consider this a bug in Org. So we should not add a workaround here.

**Comment by minad** [comment]
Okay, I will close this here. I checked the Org source and it is really unclear if the keywords should be made available via these variables. I also don't understand why we even have the separate `*-for-agenda` variables. Instead the normal keyword variables could be bound in the agenda buffer. Furthermore I don't understand why all these variables are public if they are supposed to be implementation details. Most global variables are also undocumented, which according to my standards is unnacceptable. The Org code base has grown organically and it is very chaotic. I hope that it gets cleaned up over time. There have been improvements already but progress is not as fast as one would hope. Understandably, such janitorial work does not seem to be a priority of the maintainers. My approach is usually to refactor a bit and clean up before adding new functionality, but this is easier said than done for a large system with a long history.

**Comment by protesilaos** [comment]
> Okay, I will close this here.

Thanks!

> I checked the Org source and it is really unclear if the keywords
> should be made available via these variables. I also don't understand
> why we even have the separate `*-for-agenda` variables. Instead the
> normal keyword variables could be bound in the agenda
> buffer. Furthermore I don't understand why all these variables are
> public if they are supposed to be implementation details. Most global
> variables are also undocumented, which according to my standards is
> unnacceptable. The Org code base has grown organically and it is very
> chaotic. I hope that it gets cleaned up over time. There have been
> improvements already but progress is not as fast as one would
> hope.

I took a look at the code before opening this issue and could not find
an obvious point of entry (i.e. something to include/rewrite/advice-add
in the init.el).

For me the Org code base is very difficult to study.  There are
functions running in the tens or hundreds of lines and it always feels
like it is easy to miss some important detail.

I understand a major part of my problem is that I have not read the code
carefully, so this is not a strong opinion.

> Understandably, such janitorial work does not seem to be a priority of
> the maintainers. My approach is usually to refactor a bit and clean up
> before adding new functionality, but this is easier said than done for
> a large system with a long history.

I think every big, community-driven project has this constraint in one
form or another.  People are more eager to solve a problem they are
dealing with than refactor old code.  Especially when there is a clear
commitment to backward compatibility (I believe Org is supposed to work
with the current plus last two stable versions).

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by skangas** [comment]
Was this bug reported upstream? I see that org-modern still doesn't work with custom agendas running an up-to-date org-mode master branch.

**Comment by dschrempf** [comment]
Not sure if this is related, but the alignment in the custom agenda is also messed up:

![image](https://user-images.githubusercontent.com/5596239/208395733-a0c92115-bf01-4464-89f1-30a7a719217e.png)

The alignment also changes when the files (and headlines) are visited.

**Comment by minad** [comment]
@dschrempf For me everything is aligned. This probably depends on some additional settings in your config. The screenshot you've posted is also too small to tell. Can you create a minimal example which shows the issue on emacs -Q?

**Comment by AndreaOrru** [comment]
No one found a workaround for this?

**Comment by minad** [comment]
@AndreaOrru I think this should be fixed upstream in Org itself. The variables don't seem to be initialized properly, see https://github.com/minad/org-modern/issues/26#issuecomment-1065279716. You could report a bug on the Org bug tracker.

**Comment by real-or-random** [comment]
See https://lists.gnu.org/archive/html/emacs-orgmode/2023-03/msg00145.html for a patch against upstream.

**Comment by minad** [comment]
Thanks! It seems the fix got already applied in the Org main branch, see https://lists.gnu.org/archive/html/emacs-orgmode/2023-03/msg00183.html.

**Comment by dschrempf** [comment]
Sorry for bumping this, but is there a regression? I am on Org 9.6.9, and I again have misaligned TODO items and `org-todo-keywords-for-agenda` `nil`.

Adding the following snippet to my init file fixes the issue:
```elisp
  (add-hook 'org-agenda-finalize-hook
            (lambda ()
              (setq-local org-todo-keywords-for-agenda '("TODO" "NEXT" "WTNG"))))
```

Funny enough, `org-done-keywords-for-agenda` is set properly.

**Comment by minad** [comment]
@dschrempf Yes, it seems there is a regression in Org if this stopped working again. See also #158.
