### ISSUE TITLE
global-hl-line-mode on obscures hour and minute part of the timestamps

### ISSUE THREAD

**Issue by balaramadurai** [minad/org-modern#31]
Hello @minad,
  Thank you for such a wonderful package. Org does look great with your package! Kudos to you!

One minor niggle I faced was with the `global-hl-line-mode` set to `t`.

![image](https://user-images.githubusercontent.com/13183107/159854559-d44f2862-01fd-4dd4-a4c1-a6169489b285.png)

When I take the cursor to the line with the timestamps
![image](https://user-images.githubusercontent.com/13183107/159854450-9f4a8381-4b78-4f51-bcf2-6efa3be2c82c.png)

I work with `modus-operandi` as my theme. AFAIK, I have customized the variable-pitch faces.

Please let me know if you need any other info from me to help solve this for us.

Thanks and have a nice day!
Bala

**Comment by minad** [comment]
Thanks! Unfortunately there doesn't seem to exist a solution for this problem. The hl-line overlay background color always takes precedence. See also https://emacs.stackexchange.com/questions/10445/hl-line-mode-hide-background-how-to-avoid-this. But I am afraid we have to close this as wontfix.

**Comment by minad** [comment]
We can use `:distant-foreground` to avoid obscuring the timestamp. The result is still not pretty but at least the time stamps stay readable. See https://github.com/minad/org-modern/commit/c5fcbf86f2db066cdf9d0444eec7d87352c25149.

**Comment by balaramadurai** [comment]
Thanks @minad for your wonderful ideas! It turns out that I had `global-prettify-mode` on and then it does this whacky color scheme. Once, I turn it off, there is no issue. 

![image](https://user-images.githubusercontent.com/13183107/160369116-023a8a8c-2c1f-41b3-8ae9-6d4ca6e208b8.png)

with `global-hl-line-mode` on
![image](https://user-images.githubusercontent.com/13183107/160369313-1db176cb-3d1c-44a7-9ada-c66af4fc9842.png)


Thanks again!
Bala
