### ISSUE TITLE
Heading incorrectly fontified if it has :: and tags

### ISSUE THREAD

**Issue by vizs** [minad/org-modern#32]
Take a heading that looks like,

```
* Heading :: test one two :test:
```

Here, the tag is "test" but "test one two" are also fontifed as tags.

Screenshot: http://0x0.st/oNh7.png

**Comment by vizs** [comment]
P.S. what about only allowing the characters that org-tag-re does?

**Comment by minad** [comment]
Good point, see https://github.com/minad/org-modern/commit/1605ffc284421e46598766ded6aad1309987c6ff.
