### ISSUE TITLE
No table styling in example blocks?

### ISSUE THREAD

**Issue by enricoflor** [minad/org-modern#33]
Hi,

As far as I understand, literal example blocks in org-mode (`#+begin_example`) are meant for text that does not receive any markup.  However, org-modern renders a "column" of pipes like
```
  |
  |
  |
```
as if it was part of a table (i.e. with a solid vertical line), even in literal example blocks. Is this the intended behavior?
Thanks for the great package(s)!

**Comment by minad** [comment]
You can quote Org syntax with comma in example blocks, see https://irreal.org/blog/?p=5503. For some reason this is required by Org for headline stars. But it seems that tables are indeed not highlighted in example blocks. Overall the treatment in these example blocks seems a bit inconsistent.

~~
#+begin_example
| a | b | c |
| a | b | c |
| a | b | c |
#+end_example
~~~

org-modern could do a bit better here. But I don't know how org-mode manages the distinction in the Org font locking setup. I'd appreciate some insight here. The same issue affects org-modern styling of lists and of other syntax elements.

**Comment by enricoflor** [comment]
Thanks! [`1246641`](https://github.com/minad/org-modern/commit/1246641dd0433b32f563eb1f0fb8c197128c6f84) solves the issue for me and I couldn't find problems with it!

**Comment by vizs** [comment]
Good day, Daniel.

I wonder if a better solution to the problem in this general area is to add org-modern's font-lock-keywords to the variable `org-font-lock-extra-keywords` using the hook `org-font-lock-set-keywords-hook`.

I use this hook in my personal configuration to fontify horizontal rules and this rule is not applied in an example block:

```
(defun vz/org-fontify-horizontal-break ()
  (push '("^[[:space:]]*\\(------*\\)\n"
          (0 (progn
               (put-text-property (match-beginning 1) (match-end 1)
                                  'display (make-string (- (match-end 1) (match-beginning 1)) ?\s))
               (put-text-property (match-beginning 1) (match-end 0)
                                  'face '(:strike-through t :extend t)))))
        org-font-lock-extra-keywords))

(add-hook 'org-font-lock-set-keywords-hook #'vz/org-fontify-horizontal-break)
```

Maybe you considered this but decided against it?  Anyway, I thought this would be worth mentioning.

You can see a screenshot here: http://0x0.st/oSS0.png

**Comment by minad** [comment]
@vizs Could be that this would work better. I am not that much into the org code base, so I don't recall if I considered this or not. You can probably answer this better than me. Did you test moving all (or most) org-modern--font-lock-keywords to org-font-lock-extra-keywords? If this works well we could change the approach. In that case, feel free to create a PR.

**Comment by vizs** [comment]
Sure, I will do some tests on my side and see where it leads us to.

**Comment by minad** [comment]
There is also `org-font-lock-set-keywords-hook`. Maybe that could be used as well?

**Comment by vizs** [comment]
That's what I'm doing.  But now, I'm unsure how to remove the org-modern keywords when you disable the mode :upside_down_face:

**Comment by minad** [comment]
Ah lol yes, I didn't read your snippet.

**Comment by vizs** [comment]
That hook is called before org-mode-hook is run so doing this way would make org-modern a global minor mode instead (IIUC).  But I made a new hook that was basically `(setq org-font-lock-extra-keywords (all the org modern stuff here))` but that failed with errors in redisplay ... :upside_down_face: and I am not looking forward to debugging that (i.e., if there's even a sane way to do so!).
