### ISSUE TITLE
Not getting the vertical line around the source blocks

### ISSUE THREAD

**Issue by dmitrym0** [minad/org-modern#36]
Apologies for the dumb question, but I seem to remember that there's a name for this... it's not "gutter", but similar. I suspect an interaction with my config. I'm using the `modus vivendi` theme.

**Comment by minad** [comment]
The border is shown in the fringe. It is necessary to enable a fringe to see this.

**Comment by minad** [comment]
No it should work independently of the font. But I suggest you try a minimal configuration as given in the README and investigate the issue from there. It is hard to tell which other settings could potentially interfere with `org-modern-mode`.

**Comment by Thaodan** [comment]
Is it possible to make org-modern not break `org-adapt-indentation` ? I've noticed that when using this the src block also should be indented however org-modern breaks that and always overwrites the section with zero indent.

**Comment by minad** [comment]
@Thaodan You could set `org-modern-block-fringe` to nil and configure `org-modern-block-name` as you like, for example with Unicode symbols as substitutes for the begin/end keywords.

**Comment by Thaodan** [comment]
Hm why would I do that? I like the defaults I just don't want to override the 
identation that was already set.

**Comment by minad** [comment]
@Thaodan Well, `org-modern-block-fringe` isn't compatible with indentation, neither with `org-adapt-indentation` nor `org-indent-mode`. The reason is that the vertical line is drawn in the fringe, so it is always far on the left side of the window, which doesn't look good with indentation. So you have to make a choice. You could also try https://github.com/jdtsmith/org-modern-indent, but afaik it is only supposed to work with `org-indent-mode`.

**Comment by Thaodan** [comment]
I don't care how it looks, it looks fine but when ever I edit the src-block 
the indentation 0 until I call indent-region.

**Comment by minad** [comment]
@Thaodan I don't understand your issue then.

**Comment by Thaodan** [comment]
That the indent of the physical file changes not just how it looks,
It just don't change the look of the source code section but also remove the 
indent whenever the file is changed on these sections.
