### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by domas-v** [minad/org-modern#38]
Hello.

I was trying to install `org-modern` via `use-package` (as well as the emacs' `package-install`), but got an error message:

Debugger entered--Lisp error: (file-error "http://melpa.org/packages/org-modern-20220325.1506..." "Not found")

Is this package still available?

EDIT: the error I got when tried `package-install` 
![image](https://user-images.githubusercontent.com/30794128/162036022-dd8ab339-9280-4ef4-a940-2f2c06debbd8.png)

**Comment by minad** [comment]
I assum that you have to refresh the package archive with `M-x package-refresh-contents RET`.

**Comment by domas-v** [comment]
Thank you! Forgot about that
