### ISSUE TITLE
temporary outdent of previous line when editing

### ISSUE THREAD

**Issue by aspiers** [minad/org-modern#39]
I'm seeing a weird display artifact when I edit the bottom line (item two) in the below example:

```org
* header
*** item one
*** item two
```

In this case, after every single edit of the "item two" line, the indent for item one vanishes (i.e. the whole line shifts left), and then is restored to the correct position about one second later.

**Comment by minad** [comment]
Please give a minimal reproducible including a configuration for emacs -Q. Do you use the `org-indent-mode`, which is incompatible with `org-modern-mode` as mentioned in the README?
