### ISSUE TITLE
No agenda styling in "Agenda and all TODOs"

### ISSUE THREAD

**Issue by seagle0128** [minad/org-modern#41]
While using `C-a a n`, no agenda styling, although enabled `org-modern-global-mode`.

BTW:  The name `org-modern-global-mode` is confusing to me 😢

**Comment by minad** [comment]
> While using C-a a n, no agenda styling, although enabled org-modern-global-mode.

Duplicate #26. It is an upstream bug.

> The name org-modern-global-mode is confusing to me

You are right. The naming convention `global-org-modern-mode` seems much more common. I wil look into this.

**Comment by seagle0128** [comment]
Thank you! I didn't see that issue somehow. Apologize for it!

**Comment by seagle0128** [comment]
I agree totally. But the workaround would be better before the issue is addressed by upstream.

**Comment by seagle0128** [comment]
I agree totally. But the workaround would be better before the issue is addressed by upstream.

**Comment by minad** [comment]
> I agree totally. But the workaround would be better before the issue is addressed by upstream.

Not necessarily. If we add workarounds all over the place, the root issues will never get fixed. Generally I treat an acknowledged upstream bug report as a necessary precondition before adding a workaround.

**Comment by seagle0128** [comment]
Well, I think I didn't express clearly. I didn't suggest to make a workaround inline. If the workaround is provided separately, users could make the choice themselves. I don't think the issue can be fixed by upstream soon.

> It seems you accidentally submitted your comment three times. I deleted these duplicate comments.

It should be the network issue 😢
