### ISSUE TITLE
Scope of org dynamic block "columnview" is not being taken into account when org-modern-mode is enabled

### ISSUE THREAD

**Issue by timinou** [minad/org-modern#44]
Hello!

When I update my columnview dblock with org-modern enabled, it doesn't take into account the `:id local` option, so it inputs all the headings in the whole file. Deactivating org-modern-mode makes :id local work again.

## Steps to reproduce
1. Add a columnview dblock under a headline that has items underneath. Mine is:
    ```elisp
    #+BEGIN: columnview :format "%TODO %ITEM %CLOCKSUM{:} %EFFORT{:}" :id local
    #+END: columnview
    ```
2. Update it at point (`C-c C-x C-u`)
4. Deactivate org-modern-mode and update it again.

Thanks!

**Comment by minad** [comment]
I am not familiar with columnview. Can you give me an actual example I can try?

**Comment by minad** [comment]
Okay, I tried it on a file of mine. I cannot reproduce the issue. It is unclear how org-modern would be involved here since org-modern is just font-locking. As such it should not affect the columnview dynamic block update. Please try with emacs -Q and try to narrow down the issue.

**Comment by petermao** [comment]
@timinou I had a similar problem and Claude traced it to the fold state of the heading that your `:id` points to.  I'm in the process of generating a minimal example to submit as a bug/documentation issue in org.
