### ISSUE TITLE
Faces and colors of org-todo states

### ISSUE THREAD

**Issue by AtomicNess123** [minad/org-modern#45]
Nice package! I wonder how to change the colors of TODO statuses. They are altered when I use org-modern.
Thanks!

**Comment by minad** [comment]
See `org-modern-todo-faces`.

**Comment by AtomicNess123** [comment]
Thanks. I see that

```
  (setq org-modern-todo-faces
    ’(("TODO" :background "red"
                :foreground "yellow")))
```

However, when I turn the org modern on, it is different from those colors.

**Comment by AtomicNess123** [comment]
I see. The comma in `’` (before (("TODO") is actually wrong. It should be `'` in the org-modern.el.

**Comment by minad** [comment]
The help buffer is the problem. The docstring itself is correct. I fixed this in https://github.com/minad/org-modern/commit/42cb064f9d31adaf00168f18072cec0206b9737c.
