### ISSUE TITLE
Breaks org-table-toggle-coordinate-overlays

### ISSUE THREAD

**Issue by DamienCassou** [minad/org-modern#46]
The command `org-table-toggle-coordinate-overlays` (accessible from <kbd>C-c }</kbd>) doesn't work well with org-modern.

If we start from this table:
![2022-04-20-133147](https://user-images.githubusercontent.com/217543/164221444-bef74214-63e9-4734-b988-54ccb4c2233b.png)

and activate the coordinate overlays, we get:

![2022-04-20-133134](https://user-images.githubusercontent.com/217543/164221439-6b78d906-fe42-44d1-8612-4ebc7b47cb6b.png)

As you can see:
1. columns don't display their coordinates (`$1`, `$2` and `$3`)
2. the horizontal rule doesn't display its coordinate (`I*1`)
3. the horizontal rule has moved to a weird place

Here is the result without org-modern:

![2022-04-20-133203](https://user-images.githubusercontent.com/217543/164221447-e6083bfe-25dc-40f1-8bc8-f27218a06ee4.png)

**Comment by minad** [comment]
I don't think this issue can be solved since the overlay and org-modern both want to apply their styling to the table. You can use this:

~~~ elisp
(advice-add #'org-table-toggle-coordinate-overlays
            :after (lambda ()
                     (org-modern-mode (if org-table-overlay-coordinates -1 1))))
~~~

**Comment by minad** [comment]
I could try to somehow modify the org-modern table styling depending on if the overlays are enabled. However such an approach would be quite a complication and there are more important issues regarding improved table styling, mainly pixel perfect alignment, see #43.

**Comment by DamienCassou** [comment]
I understand, thank you.
