### ISSUE TITLE
+ is fontified by org modern in src block

### ISSUE THREAD

**Issue by Inc0n** [minad/org-modern#47]
As title, I found out that + character is fontified by org-modern in src block.

**Comment by minad** [comment]
Duplicate #33

**Comment by Inc0n** [comment]
As I have just experiemented that `org-superstart` also suffer from this issue.

**Comment by Inc0n** [comment]
It seems that the OP who posted the issue in https://github.com/minad/org-modern/issues/33, is satisfied with the fix, whereas, I still see this fontified + in src blocks in `org-modern-20220422.940/`, would it be more appropriate to close the other one and keep this open?
