### ISSUE TITLE
Error when running org-todo

### ISSUE THREAD

**Issue by rhstanton** [minad/org-modern#49]
When I type  C-c C-t to run org-todo, in order to add TODO to a header, I get the following error:
```
org-entry-get-with-inheritance: Symbol’s value as variable is void: org-property-separators
```
This works fine when org-modern is not loaded.

**Comment by rhstanton** [comment]
Odd. It's stopped happening... I'll have to check into this further.

**Comment by minad** [comment]
Okay. Please check that you can reproduce this with emacs -Q.
