### ISSUE TITLE
emacs -Q example doesn't run

### ISSUE THREAD

**Issue by notuntoward** [minad/org-modern#50]
If I start emacs with emacs -Q, and then run the code in the emacs -Q example, I get the error:

> eval-buffer: Symbol’s function definition is void: modus-themes-load-operandi

Someone new to emacs will be confused by that.

**Comment by japhir** [comment]
which version of emacs do you have? Modus themes are included in emacs since a recent version (don't know which off the top of my head)

**Comment by notuntoward** [comment]
Oh yeah, I should have said that:  27.2

**Comment by japhir** [comment]
Yep, "The Modus themes are distributed with Emacs starting with version 28.1."

**Comment by minad** [comment]
It works on Emacs 28 out of the box. The README mentions the Modus themes so it should be possible for everyone to figure out the issue.
