### ISSUE TITLE
add other org-modern styles to org-agenda?

### ISSUE THREAD

**Issue by japhir** [minad/org-modern#53]
Currently it seems that only the todo-keywords (`TODO`, `NEXT`, etc.) and progress indicators (`[4/6]`) are styled when I look at the org-agenda, while the priority cookies (`[#A]`, `[#B]`, etc.)  and the tags (e.g. `:Work:@computer:`) are not.

Did I miss any user options or make some other mistake? My config is basically: 

```emacs-lisp
  (use-package org-modern
    :after org
    :config (global-org-modern-mode))

;; with some of this
(defface org-todo-next
    ;; face config
    )

;; and then this
(setq org-modern-todo-faces
  '(("NEXT" . org-todo-next)
    ("WAIT" . org-todo-wait)
    ; ...
   ))
```

**Comment by japhir** [comment]
Weirdly, it seems to update the agenda lines after I visit the file that the offending agenda item belongs to (by pressing <tab> on the agenda) and then re-making the agenda. It doesn't seem to update the lines for the whole file at once, but does so one task at a time. I don't understand why.

**Comment by minad** [comment]
Yes, we could add more org-agenda styling. Feel free to give it a try!
