### ISSUE TITLE
Agenda styling

### ISSUE THREAD

**Issue by minad** [minad/org-modern#6]

**Comment by DivineDominion** [comment]
Any plans you like to share or help you could need? 🙃

**Comment by minad** [comment]
No plans and no code to share just yet. My agenda is not tuned or configured much so I should maybe first explore which tweaks are available ootb. I think @protesilaos recently made a video about his adjustments.

I guess in the end we would have to add a separate `org-modern-agenda-mode` to org-modern.el, which will be implemented similarly as the current `org-modern-mode`. These two modes could probably share a lot of code. Any help working on that would be greatly appreciated! (It is likely that I will also submit this package to GNU ELPA, so it is better if you have the copyright assignment or if you are willing to get it. I hope that's not a turn off.)

**Comment by protesilaos** [comment]
My tweaks only concern the overall structure, which now looks like this
(explanation in parentheses):

```
* Important tasks without a date  (i.e. TODO [#A])

... list of entries

* Pending scheduled tasks (past schedule; not done yet)

... list of entries

* Today's agenda

... list of entries

* Next three days (scheduled, deadline)

... list of entries

* Upcoming deadlines (+14d after the three days)

... list of entries
```

There is one or perhaps a couple minor tweaks which change the
applicable face for the "today" heading, though I think those do not
really make the buffer prettier---just me being opinionated about the
correct face in that context.

Put differently, if you have any ideas on how to improve the agenda, it
should work on my end as well.

**Comment by minad** [comment]
@protesilaos Yes, I watched your video in the meantime. It was interesting and helpful. I didn't mean to imply that your video was about styling, rather that I had not looked yet into the configurability of the agenda. Having some overview of that is helpful before considering to apply any kind of superficial styling.

**Comment by protesilaos** [comment]
> @protesilaos Yes, I watched your video in the meantime. It was
> interesting and helpful. I didn't mean to imply that your video was
> about styling, rather that I had not looked yet into the
> configurability of the agenda. Having some overview of that is helpful
> before considering to apply any kind of superficial styling.

Okay!

-- 
Protesilaos Stavrou
https://protesilaos.com
