### ISSUE TITLE
Fixed pitch for labels

### ISSUE THREAD

**Issue by agenbite** [minad/org-modern#63]
Hi, thanks for this package, makes life much beautiful! :)

What is the best way to disable the use of variable pitch for modern style labels? My variable pitch font (ETBembo) is too convoluted for labels, and I'd like labels to stay fixed width...

**Comment by minad** [comment]
Thanks! See the readme for how to adjust face family:

~~~ elisp
(set-face-attribute 'default nil :family "Iosevka")
(set-face-attribute 'variable-pitch nil :family "Iosevka Aile")
(set-face-attribute 'org-modern-symbol nil :family "Iosevka")
~~~

Then you can look at all the faces which are defined by `org-modern` and adjust them according to your preferences.
