### ISSUE TITLE
Missing ends on top and bottom of src block brackets

### ISSUE THREAD

**Issue by GaryDahl** [minad/org-modern#64]
In the introduction screenshot on the readme.org page, the bracket next to src blocks looks like a tall [ character with corners on the top and bottom.  However, I'm seeing this rendered without the corners on the top and bottom: more like a tall | character.  

I tried looking for a way to customize this without success.  So I next tried running the provided emacs -Q minimum setup code to reproduce this kind of image, and found the same problem: with these brackets still looking like | rather than [.  

I'm using GNU Emacs 28.1 on a Mac... and will be interested to hear if there are other variables that might account for this difference.  Or if there is anything that I can try doing to change these |s into [s, I'll be interested to hear.  Thanks.

**Comment by minad** [comment]
I am afraid I cannot help you with that. Maybe it is a Mac-specific or an issue specific to your font/resolution settings? What did you try exactly? For me it works when I execute these three steps:

1. emacs -Q (28.1 on Linux)
2. M-x global-org-modern-mode
3. Open example.org

The fringe bitmaps are defined here:

https://github.com/minad/org-modern/blob/b352680d9ee8c6e6966cc21d595513c3595e3bb7/org-modern.el#L470-L472

**Comment by tachanka61** [comment]
I also have the same issue, Linux, Emacs 28.1 (Doom Emacs)

org-modern was installed via `packages.el`

Here are some screenshots:

- Doom Emacs:
![image](https://user-images.githubusercontent.com/89523794/173196473-4cc3aced-8635-4e43-8e72-5f1dd05e49fa.png)

- Vanilla Emacs launched with `emacs -Q -l org-modern.el`
![image](https://user-images.githubusercontent.com/89523794/173196522-6df2af8c-7f9a-4b4d-919c-2469353f6d15.png)

**Comment by GaryDahl** [comment]
Thanks for the quick response!  Although my troubleshooting efforts have not been very fruitful,I think I have found a work-around.  I tried changing the bitmap definitions to different bit patterns, and also tried swapping the definitions for block-inner vs block-begin.  None of these changes resulted in a different rendering.  This led me to believe that the problem might be in the specification or rendering of the text properties that they are added to.  But I was having difficulty finding good documentation an examples to help inform further experiments.

I did however find that the [org-modern-indent package](https://github.com/jdtsmith/org-modern-indent/) renders these brackets using text characters instead of fringe bitmaps.  So for the time being, I'll just use that package on top of org-modern.

**Comment by minad** [comment]
I think the issue in your cases is just that you use a small font. I can confirm your issue when I scale down multiple times with C-x C--. There is definitely no issue with the property specification, since org-modern works perfectly well for me. You can try alternative fringe bitmap definitions.

~~~ elisp
(define-fringe-bitmap 'org-modern--block-inner (make-vector 1 #x80) nil nil '(top t))
(define-fringe-bitmap 'org-modern--block-begin (vconcat (make-vector 10 0) [#xFF] (make-vector 117 #x80)) nil nil 'top)
(define-fringe-bitmap 'org-modern--block-end (vconcat (make-vector 117 #x80) [#xFF] (make-vector 10 0)) nil nil 'bottom)
~~~

**Comment by tachanka61** [comment]
Thank you for your response, I've tried to zoom text in Emacs and corners appear!

![image](https://user-images.githubusercontent.com/89523794/173201957-6b757371-37c5-49a8-85d4-512680cace3d.png)
