### ISSUE TITLE
[FEATURE REQUEST] Keep the space before styled source blocks

### ISSUE THREAD

**Issue by stardiviner** [minad/org-modern#65]
When without org-modern, the source blocks which has spaces ahead, it shows the indentation. it looks likes this:

<img width="498" alt="image" src="https://user-images.githubusercontent.com/378699/173239517-52e1acf3-6286-4f05-9cd1-85743dfc2fb3.png">

But after enabled org-modern-mode, the indentation spaces are gone.

<img width="474" alt="image" src="https://user-images.githubusercontent.com/378699/173239561-dd6704d1-2a11-443c-9bcf-635dcb038daa.png">

Hope org-modern can keep the indentation spaces.

I really like org-modern, really awesome work. Thanks very much. @minad

**Comment by minad** [comment]
That's not possible since the source block bracket is displayed in the fringe, we cannot indent that. You may want to disable block styling or try @jdtsmith's org-modern-indent package. Maybe we can also merge back some code from there such that indented source blocks and org-indent-mode works too.

**Comment by stardiviner** [comment]
> That's not possible since the source block bracket is displayed in the fringe, we cannot indent that.

I see. Thanks for answering.

> You may want to disable block styling or try @jdtsmith's org-modern-indent package.

I tried the org-modern-indent mode. It does not indent the spaces before the source block. It works for `org-indent-mode` and put fringe line to source block ahead which looks more elegant and better.

> Maybe we can also merge back some code from there such that indented source blocks and org-indent-mode work better.

If you merge this org-modern-indent style. I think keeping spaces before source block is possible. But I don't know whether it's complicated. If so, maybe not worth implemented my needs.

Regards,
stardiviner.

**Comment by stardiviner** [comment]
As a record note.

I change the space in `org-modern--block-fringe` function like bellowing:

```diff
modified   org-modern.el
@@ -468,51 +468,51 @@ You can specify a font `:family'. The font families `Iosevka', `Hack' and
                                         (if (= 0 (mod i 2)) sp1 sp2)))))))))
 
 (defun org-modern--block-fringe ()
   "Prettify blocks with fringe bitmaps."
   ;; Do not add source block fringe markers if org-indent-mode is
   ;; enabled. org-indent-mode uses line prefixes for indentation.
   ;; Therefore we cannot have both.
   (unless (bound-and-true-p org-indent-mode)
     (save-excursion
       (goto-char (match-beginning 0))
       (add-text-properties
        (point) (min (line-end-position) (point-max))
        '(wrap-prefix
-         #(" " 0 1 (display (left-fringe org-modern--block-begin org-block-begin-line)))
+         #("    " 0 1 (display (left-fringe org-modern--block-begin org-block-begin-line)))
          line-prefix
-         #(" " 0 1 (display (left-fringe org-modern--block-begin org-block-begin-line)))))
+         #("    " 0 1 (display (left-fringe org-modern--block-begin org-block-begin-line)))))
       (forward-line)
       (while
           (cond
            ((eobp) nil)
            ((save-excursion
               (let ((case-fold-search t))
                 (re-search-forward
                  "^[ \t]*#\\+end_" (line-end-position) 'noerror)))
             (add-text-properties
              (point) (min (line-end-position) (point-max))
              '(wrap-prefix
-               #(" " 0 1 (display (left-fringe org-modern--block-end org-block-begin-line)))
+               #("    " 0 1 (display (left-fringe org-modern--block-end org-block-begin-line)))
                line-prefix
-               #(" " 0 1 (display (left-fringe org-modern--block-end org-block-begin-line)))))
+               #("    " 0 1 (display (left-fringe org-modern--block-end org-block-begin-line)))))
             nil)
            (t
             (add-text-properties
              (point) (min (1+ (line-end-position)) (point-max))
              '(wrap-prefix
-               #(" " 0 1 (display (left-fringe org-modern--block-inner org-block-begin-line)))
+               #("    " 0 1 (display (left-fringe org-modern--block-inner org-block-begin-line)))
                line-prefix
-               #(" " 0 1 (display (left-fringe org-modern--block-inner org-block-begin-line)))))
+               #("    " 0 1 (display (left-fringe org-modern--block-inner org-block-begin-line)))))
             (forward-line)
             t))))))
 ```

Then the block looks like this:

<img width="506" alt="image" src="https://user-images.githubusercontent.com/378699/173243439-9ec65337-758f-40a7-b7a4-276d16c26626.png">

Need to study org-modern-indent source code.

**Comment by jdtsmith** [comment]
> Maybe we can also merge back some code from there such that indented source blocks and org-indent-mode work better.

Perfectly happy to go this route and point people here.  BTW, I also need to disable `org-modern-hide-stars` since it reduces heading indentation with org-indent, so perhaps that could be improved.

Note that `org-modern-indent` does rely on `org-indent`, since the latter sets a line-prefix which `org-modern-indent` tweaks.  

The problem with "indenting myself with spaces" is what do you do with:

```org
   #+begin_example
Not indented
   #+end_example
```

IMO the correct thing is, e.g.:

<img width="344" alt="image" src="https://user-images.githubusercontent.com/93749/173249058-63265195-8e43-4df0-9860-17a8fae38439.png">

**Comment by minad** [comment]
@jdtsmith Uuuh. I don't know how to handle such a weird indentation but the example looks off. I think the border should be indented as deep as the begin/end keywords. I am glad that I don't have these issues with the fringe. 😅

**Comment by stardiviner** [comment]
@minad Is it possible to use indentation spaces length from original block and pass them as variable into block styling function. And it will display like my upper screenshot. (I know this space gaps looks not fit intuition as fringe. Maybe provide an user custom option to toggle this behavior, and keep it disabled by default. WDYT?)

**Comment by jdtsmith** [comment]
> @jdtsmith Uuuh. I don't know how to handle such a weird indentation but the example looks off. I think the border should be indented as deep as the begin/end keywords. I am glad that I don't have these issues with the fringe. 😅

Notice the arrow; where does that go?  To treat hand-indented blocks you’d have to calculate the indent by examining the full block!  So I don’t think @stardiviner’s request is that easy.
