### ISSUE TITLE
String like "LC_ALL" shows incorrect

### ISSUE THREAD

**Issue by haoisli9** [minad/org-modern#67]
String like "LC_ALL", _ALL becomes lower than LC. that's incorrect.
how to disable "_" formater?

**Comment by minad** [comment]
Not an org-modern issue. These are normal org subscripts. Please read the org docs.

**Comment by stefan2904** [comment]
For the record: you want to customize/set the value of `org-use-sub-superscripts`.

See https://orgmode.org/manual/Subscripts-and-Superscripts.html

**Comment by minad** [comment]
Indeed. Or you can use = or ~.

**Comment by stefan2904** [comment]
But this does not help in, e.g., property values?

**Comment by refaelsh** [comment]
> But this does not help in, e.g., property values?

I am having the same issue.

**Comment by refaelsh** [comment]
For future googlers: I found this variable `org-pretty-entities` in the docs. It turns off the subscript thingy.

**Comment by g-gundam** [comment]
To follow up on what @refaelsh said, there's also a variable called `org-pretty-entities-include-sub-superscripts`.  Setting that to nil will make _ behave normally again.
```elisp
(setq org-pretty-entities-include-sub-superscripts nil)
```
