### ISSUE TITLE
False positive for internal and radio link targets

### ISSUE THREAD

**Issue by protesilaos** [minad/org-modern#68]
Hi Daniel,

Just to note that internal and radio link targets give me false positives in table formulas, such as:

```
#+TBLFM: @>$+1..$3=vmean(@<<..@>>);%.1f :: @>$1='(length (org-lookup-all ".*" '(@<<<$1..@>>>$1) nil 'string-match-p))
```

**Comment by minad** [comment]
Good point. How can we avoid this? In this case @ is in juxtaposition to the angle brackets. Can we take advantage of that or are there other cases where we get freestanding `<<` characters?

**Comment by protesilaos** [comment]
> In this case @ is in juxtaposition to the angle brackets.

It would be either `@` or `$` in formulas.  Evaluate:

```elisp
(info "(org) References")
```

Or visit: <https://orgmode.org/manual/References.html#References>.

> Can we take advantage of that or are there other cases where we get
> freestanding `<<` characters?

I think they should always be together with `@` or `$`.  Though I am not
sure if we can have `<<` characters in formulas that symbolise something
else.  That would be a mess.

An aside here.  Both the table formulas and the internal/radio links are
fairly obscure to me.  I have not seen them in the wild and am not sure
how they appear and may intersect with each other in actual documents.

**Comment by minad** [comment]
It should be possible to disable org-modern styling per element via file local variables. This will also help with conflicts.

**Comment by protesilaos** [comment]
Yes, that's true.  As I don't use those link targets myself, it would
make no difference if I disable them globally.  Just wanted you to know
abou this.
