### ISSUE TITLE
text size change messes up table vertical line alignment

### ISSUE THREAD

**Issue by dasoju** [minad/org-modern#69]
Hi
initially table is displayed correctly with the table lines correctly aligned
but when i increase or decrease font (iam using text-scale-increase) the vertical lines get mis-aligned and the table gets messed up, even after typing TAB in a cell, it doesnt fix the alignment 

The table i have has dates in some of the cells

this does not happen in original org-table

**Comment by dasoju** [comment]
I see the issue with both fixed-width and variable-width

**Comment by dasoju** [comment]
I tried with 0.4, i still see the same issue

Below is initial table 
<img width="226" alt="image" src="https://user-images.githubusercontent.com/54728201/174951561-5be6cab3-9721-4a3c-982a-42880736237f.png">

below is after i increase the text size using text-scale-increase
<img width="277" alt="image" src="https://user-images.githubusercontent.com/54728201/174951697-32376abb-d539-40ae-81fb-64dab42aba92.png">

**Comment by dasoju** [comment]
following are the settings  from my init file

(add-hook 'org-mode-hook #'org-modern-mode)
(add-hook 'org-agenda-finalize-hook #'org-modern-agenda)

(setq org-modern-table-vertical   1)
(setq org-modern-table-horizontal 1)
(setq org-modern-variable-pitch 'fixed-pitch)
(setq org-modern-timestamp '("%m/%d/%y" . "%m/%d/%y %H:%M"))
(setq org-modern-star ["◉" "○" "◈" "◇" "✳"])

**Comment by noctuid** [comment]
The initial table display with timestamps in the first column is misaligned for me with the default `org-modern-timestamp` as t and timestamps like `[2022-06-20 Mon]`.

**Comment by dasoju** [comment]
noctuid,
Thanks for the response, yes i did look at #5 and tried the following, but still couldn't resolve the issue

- Installed valign
   - tried enabling valign globally, but emacs is hanging when it loads org files (I have lot of org files with lot of tables)
   - tried enabling valign on a table only, but still the alignment issue still persists after text-scale-increase
- Added the following based on protesilaos comment, but still doesn't resolve the issue
  `(setq org-modern-label-border 1)
(eval-after-load 'org-modern-face 
  '(progn
     (set-face-attribute 'org-modern-label nil
			 :box `( :line-width (-1 . ,org-modern-label-border)
				 :color ,(face-background 'default)))
     ))
`
I see lot of potential for org-modern package (Thanks to minad !!)

**Comment by vizs** [comment]
org-modern--table uses the space display text property which isn't recalculated when you change the buffer text size with C-x C-= so yes, this issue is expected.

A simple reproducer: M-: (insert (propertize " " 'display '(space :width 4)) "aaa") RET and then do C-x C-=, the space won't increase when you increase the text size.

**Comment by minad** [comment]
See:

https://github.com/minad/org-modern/blob/5de3da1ff55b4567e9df3b234c09427aed2cbcd7/org-modern.el#L465

**Comment by dasoju** [comment]
Thanks Daniel !
will wait until  its fixed

**Comment by minad** [comment]
@dasoju It will not get fixed If nobody contributes improvements. Did you consider contributing?
