### ISSUE TITLE
Separate face for checkboxes

### ISSUE THREAD

**Issue by noctuid** [minad/org-modern#72]
I'd like to have checkboxes be bigger than they currently are without also increasing the star, keyword, etc. sizes, so it would be nice to have a dedicated face for checkboxes.

**Comment by minad** [comment]
Makes sense. We could add separate faces for all style elements which use org-modern-symbol currently. PR welcome.

**Comment by josephmturner** [comment]
+1 I would also be grateful to have larger checkboxes. Thank you for `org-modern`!

**Comment by minad** [comment]
It doesn't seem necessary to add a separate org-modern-checkbox face since you can also apply styling via the org-checkbox face.

**Comment by josephmturner** [comment]
Thank you - I will look into increasing font size.
