### ISSUE TITLE
Some symbol are different from example

### ISSUE THREAD

**Issue by drcxd** [minad/org-modern#74]
![image](https://user-images.githubusercontent.com/24535087/176669476-b6c3cc96-f82e-4cb1-99fb-f1110f686a6d.png)

Starts from the fifth level headline, the symbol displayed on my computer is different from the example. I am also using the modus-operandi theme and enabled variable-pitch font.

Also the `[#A]` is displayed differently as well. Is there any other dependency I need to install?

**Comment by minad** [comment]
The screenshot is outdated.
