### ISSUE TITLE
Background color of org-modern-todo-faces not displayed when cursor is on heading

### ISSUE THREAD

**Issue by Calvin-Xu** [minad/org-modern#76]
After `org-modern-todo-faces` is set, the appearance of TODO keywords display as expected, but the background color is gone when the cursor is anywhere on the heading line, which did not happen before the value is set.

**Comment by minad** [comment]
This happens due to hl-line-mode. You can prevent this from happening by using `inverse-video`, for example:

~~~ elisp
  (setq org-modern-todo-faces
        '(("TODO" :foreground "#009" :inverse-video t)))
~~~

But besides that, there is not much we can do. It is a limitation of hl-line-mode.
