### ISSUE TITLE
Some tags are not styled in org-agenda

### ISSUE THREAD

**Issue by JingYenLoh** [minad/org-modern#78]
I have the following config file:
```elisp
(setq org-auto-align-tags nil
      org-tags-column 0)

(global-org-modern-mode)
```

With the example org file in the following screenshot, I get the agenda view in the same image:

![image](https://user-images.githubusercontent.com/22059033/179364024-9d3af96d-ec96-4e00-85f0-e139743b4d2f.png)

**Comment by minad** [comment]
I've also observed this before. You can disable tag inheritance `(setq org-agenda-show-inherited-tags nil)`. But it would also be nice to improve the Org agenda formatting such that prettification works also for inherited tags.
