### ISSUE TITLE
Feature request: reccognize timestamp in Chinese

### ISSUE THREAD

**Issue by pinacle2000** [minad/org-modern#8]
Shows modern style with timestamp in English:
[2022-03-01 TUE 10:42]

But no in Chinese:
[2022-03-01 周二 10:42]

Or is there a way to configure it?

**Comment by minad** [comment]
It should be possible to adjust the regexp here to recognize Chinese months:

https://github.com/minad/org-modern/blob/dd7d45878f04c8aa9872ba6f6b4fb638dcba3032/org-modern.el#L482

**Comment by pinacle2000** [comment]
I tried to add "\cc" (the Chinese char regex defined by emacs I found online, but didn't work:

`
      (when org-modern-timestamp
        '(("\\(?:<\\|\\[\\)\\([0-9]\\{4\\}-[0-9]\\{2\\}-[0-9]\\{2\\}\\(?: [A-Za-z\cc]+\\)?\\)\\(\\(?: [0-9]\\{2\\}:[0-9]\\{2\\}\\)?\\(?: [.+-]+[0-9]+[hdwmy]\\)?\\)\\(?:>\\|\\]\\)"
           (0 (org-modern--timestamp)))))
`

I just have very basic knowledge on emacs. Any suggestion?

**Comment by minad** [comment]
It seems that `[[:word]]+` works. Please give it a check.

**Comment by pinacle2000** [comment]
It works, thx!
