### ISSUE TITLE
org-modern fails when fringe library is not loaded

### ISSUE THREAD

**Issue by bram85** [minad/org-modern#81]
On systems where fringe.el is not loaded (e.g. Emacs on terminal), org-modern does not load:

    File mode specification error: (void-function fringe-bitmap-p)

This is because it is not checked if `fringe-bitmap-p` presence is not checked with `fboundp`. Fixed it locally with:

```diff
diff --git a/org-modern.el b/org-modern.el
index b9a8f75..e56be02 100644
--- a/org-modern.el
+++ b/org-modern.el
@@ -510,7 +510,7 @@ You can specify a font `:family'. The font families `Iosevka', `Hack' and
   :group 'org-modern
   (cond
    (org-modern-mode
-    (unless (fringe-bitmap-p 'org-modern--block-inner)
+    (when (and (fboundp 'fringe-bitmap-p) (not (fringe-bitmap-p 'org-modern--block-inner)))
       (let* ((g (ceiling (frame-char-height) 1.8))
              (h (- (default-line-height) g)))
         (define-fringe-bitmap 'org-modern--block-inner
```

**Comment by minad** [comment]
Thanks. I applied your fix. However org-modern won't work well on the terminal. We could as well just fail with an error or turn org-modern-mode into a no-op.
