### ISSUE TITLE
Missing horizontal lines in tables with 20220730.827

### ISSUE THREAD

**Issue by CognDiss** [minad/org-modern#83]
On Macos.  I just upgraded my emacs (v29) app which I get from macports.   At the same time I upgraded org-modern to 20220730.827.

There are no horizontal lines in any of my tables.  This was working beautifully before I did the upgrades.

There are also no horizontal lines in the example.org using the 'emacs -Q' setup in README.org.   The only change I made to the setup was to comment out the modus-themes-load-operandi line which was not defined on my setup for some reason.

![Screen Shot 2022-08-02 at 9 56 58 PM](https://user-images.githubusercontent.com/12613612/182508278-d2eff3c0-38ad-4bc9-b56d-50bf95d984b1.jpg)

**Comment by minad** [comment]
Sounds like a bug/regression of the Mac port. Please report it there.

**Comment by bestlem** [comment]
I think that there is a misunderstanding here. The port by mituharu (which is often referred to as macport) has not been upgraded beyond emacs 28.1 yet. I think the OP is referring to the Macports package manager which just builds gnu emacs. The current build is from emacs main branch at 2022-07-28.

**Comment by minad** [comment]
Okay, I see. In that case, it could be that there is a Mac-specific regression on Emacs master and it should be reported there. For the report it would be best to prepare a minimal example which shows the regression and which relies only on emacs -Q.

**Comment by bestlem** [comment]
Just to confirm I use GNU Emacs built by macports but on the stable 28.1 release and I do get the lines

**Comment by CognDiss** [comment]
Horizontal lines were properly displayed with the previous v29 version from
macports.org.   I will try to come up with a minimal test case to report to
emacs devel but it may be a week or 2 ...

*--tony*

**Comment by bestlem** [comment]
I have for other reasons started using emacs 29 built by MacPorts and I agree the horizontal lines are missing but the vertical lines look OK as in my previous view. Perhaps it is the font the OP is using for that issue.

**Comment by CognDiss** [comment]
whoohoo!  I've just realized the horizontal lines are now present.  I do not know when they reappeared, it could have been a week or more ago as I've not been using my laptop very much recently.  but I haven't updated emacs since mid-november and haven't updated any emacs packages in almost as long.  So I'm perplexed...

Hopefully they are now showing up for other users as well.
