### ISSUE TITLE
Is it possible to have dynamic bullets?

### ISSUE THREAD

**Issue by zhenhua-wang** [minad/org-modern#86]
This is not an issue. It is just an idea. [org-bars](https://github.com/tonyaldon/org-bars) and [org-visual-outline](https://github.com/legalnonsense/org-visual-outline) have implemented dynamic bullets, where we can set different symbols for unfold and folded headings. It would be good feature to have in `org-modern` too.

**Comment by minad** [comment]
I've considered this before, but I think that's not easily possible to implement using font locking. Therefore this is out of scope.

 But feel free to experiment. As long as an efficient implementation is possible, why not? If you are interested please propose a PR.
