### ISSUE TITLE
No horizontal line in tables

### ISSUE THREAD

**Issue by summeremacs** [minad/org-modern#87]
Hi, I'm having an issue with org-modern tables. The horizontal line isn't showing up. I'm not a coder but I'll give you what I can about my setup if you could help? Thanks 🙃

Mac M1 Max with Emacs 28.1 Railwaycat
Theme: ef-summer from Prot
Font: Cartograph (which is fixed width and I use it for variable pitch too)

The vertical lines show up fine and so far align great. But the horizontal lines are invisible.

Is there some sort of setq thing that I can use to re-define a vertical line maybe?

**Comment by minad** [comment]
Duplicate #83. This is likely a bug in the display implementation of Emacs on Mac. We cannot do much about it here.
