### ISSUE TITLE
task and tag boxes problem

### ISSUE THREAD

**Issue by BR00l** [minad/org-modern#89]
Hello! I have installed the package recently, and everything is fine except some white lines on top of the TODO and tag boxes.
I include some screenshots showcasing the problem.

White lines on top of the boxes, theme is doom-one.
![image](https://user-images.githubusercontent.com/454575/185805684-c1500767-8065-4a85-a1de-b6019352cc80.png)

Everything is fine on ef-night theme.
![image](https://user-images.githubusercontent.com/454575/185805741-e21c6012-5537-4526-8f85-2614775644bf.png)

Here, at default theme, overlaping boxes dont create the effect on the previous themes.
![image](https://user-images.githubusercontent.com/454575/185805792-9f8d1b94-cdc0-450b-be07-fd01ad1c587d.png)

And lastly this is doom-nord, with the same effect.
![image](https://user-images.githubusercontent.com/454575/185805861-7be1533e-64c7-463f-aa8e-fa0dd26b8cf7.png)

Is is possible to remove those white marks?
Maybe its caused by each theme, but sadly, my skills are not still there to be able to identify the problem :)

**Comment by minad** [comment]
> White lines on top of the boxes, theme is doom-one.

These lines go away if you disable and reenable global-org-modern-mode after switching themes. You can also disable the effect by setting org-modern-label-border to nil.

**Comment by minad** [comment]
> These lines go away if you disable and reenable global-org-modern-mode after switching themes.

Switching themes is supported since https://github.com/minad/org-modern/commit/d6307eefcc1576579f21defb1a18cac2f693a194.
