### ISSUE TITLE
Can not recognize timestamp with duration

### ISSUE THREAD

**Issue by pinacle2000** [minad/org-modern#9]
OK with:
[2022-03-01 TUE 10:42]

Not with:
[2022-03-01 TUE 10:42-11:00]

**Comment by astoff** [comment]
Related but not the same: data ranges are not parsed:

![image](https://user-images.githubusercontent.com/6500902/156139690-40730d45-6c01-4d9d-b04a-9e3bc22392a5.png)

**Comment by minad** [comment]
Yes, all known issues. Please create a PR which recognize more. But @astoff I am not sure how to format long date ranges like this nicely.

**Comment by minad** [comment]
For now I fixed the timestamp durations. Regarding date ranges, I am not sure how to proceed. We should discuss that in a separate issue. The current design is inspired by https://github.com/rougier/svg-tag-mode, which is quite opinionated.

**Comment by astoff** [comment]
I think the case of date ranges is simple: render the `--` as an en-dash, and apply some faces (perhaps white background and dark gray text). So like this, but not as black:
![image](https://user-images.githubusercontent.com/6500902/156185813-575e4a5b-81a5-4c3c-ae5c-8ca7311d5d10.png)
