### ISSUE TITLE
Source Block guide lines don't show with org-indent-mode turned on

### ISSUE THREAD

**Issue by yusi1** [minad/org-modern#90]
Hi!
I have noticed that the source code block guide lines don't show with `org-indent-mode` turned on, is there any way to get them back with it turned on?

Here are some screenshots to show what I mean:
`org-indent-mode` turned off (guidelines appear):
![220821_204434](https://user-images.githubusercontent.com/82241382/185808299-b043cabd-3a2b-491f-81fb-5a1d3483dca1.png)
`org-indent-mode` turned on (guidelines disappear):

**Comment by minad** [comment]
See #7

**Comment by yusi1** [comment]
sry had to close it bcs I revealed sensitive information

**Comment by yusi1** [comment]
thanks

**Comment by yusi1** [comment]
could you somehow delete this issue?
