### ISSUE TITLE
Boxes around keywords, tags, times, etc are too short

### ISSUE THREAD

**Issue by pard68** [minad/org-modern#91]
The boxes around special words (TODO faces, tags, timestamps, priorities, maybe others) are not as they appear in the example. I noticed that when I switch themes there are some white lines above and below these boxes. And in #89 it was mentioned that by toggling org-modern those lines go away. I observed that this is true, but #89 suggests the white lines will be replaced by the respective background color, however instead it appears that the white lines are replaced back the background color for the document and not the background color of the box.

Not sure if this is intentional, a bug, or a setting I need to fix, however it's making org-modern somewhat difficult to use and definitely difficult to read. Here is a screenshot of what I am seeing, using the same theme and settings (minus font, which I did try using to no avail) as the example screenshots in the README:

![Screen Shot 2022-08-24 at 10 46 40 AM](https://user-images.githubusercontent.com/18722936/186463296-b2363f75-01e0-4686-82b5-fd53cf08594b.png)

**Comment by minad** [comment]
Set org-modern-label-border to nil as mentioned in #89.

**Comment by minad** [comment]
> ...however instead it appears that the white lines are replaced back the background color for the document and not the background color of the box.

This is intentional in order to achieve a "button effect". Please don't reopen the same issue again. Instead comment on an existing issue if something is unclear, in this case #89.

**Comment by minad** [comment]
> I noticed that when I switch themes there are some white lines above and below these boxes. 

Switching themes is supported since https://github.com/minad/org-modern/commit/d6307eefcc1576579f21defb1a18cac2f693a194.
