### ISSUE TITLE
Avoid "internal link" and "radio target" stylize in source blocks.

### ISSUE THREAD

**Issue by stardiviner** [minad/org-modern#92]
![CleanShot 2022-09-02 at 11 39 54@2x](https://user-images.githubusercontent.com/378699/188054618-4d5c2720-76d6-4850-9c2c-7510a79c0871.png)

Like in upper screenshot, the `<<link>>` and `<<<link>>>` is stylized by org-modern. Hope org-modern can skip source blocks etc positions which should not be stylized.

**Comment by minad** [comment]
Duplicate #33
