### ISSUE TITLE
Emphasized link renders higher level headings unfoldable

### ISSUE THREAD

**Issue by sbstratos79** [minad/org-modern#93]
If a link has been emphasized to be bold, italics etc., all the higher level headings in the tree excluding the sub-heading that contains the actual link cannot be expanded. Disabling `org-modern-mode` fixes the issue so it has something to do with this package.

[Here's a video](https://user-images.githubusercontent.com/4395586/188806642-7bfa068f-c5fe-4f1d-a078-54dea748fa58.mp4)  illustrating the issue.

**Comment by minad** [comment]
Please provide a minimal Org file and a minimal configuration starting from emacs -Q. I cannot investigate or reproduce this otherwise.

**Comment by sbstratos79** [comment]
> Please provide a minimal Org file and a minimal configuration starting from emacs -Q which clearly demonstrate the issue. I cannot investigate or reproduce this otherwise.

I tested the same file with `emacs -Q` and org-modern-mode and I can't reproduce this behavior. There's probably some issue with my config which is causing org-modern-mode to act strange. Thanks for the reply. I will report back if I figure out the options that are causing this behavior.
