### ISSUE TITLE
Possible to keep heading indent?

### ISSUE THREAD

**Issue by linuxclef** [minad/org-modern#96]
Hi @minad! Thanks for creating `org-modern`. I love it... with one exception...

I really want to maintain the tree structure of my org files (the heading/header/bullet/star indents), but `org-modern` removes all the indents so the bullets are all aligned in the first column.

I actually hacked a solution that was to do this (note the increase number of spaces at the start of each string):

```lisp
(setq org-modern-star '("◉" " ○" "  ◈" "   ◇" "    ✳"))
```

This almost works: it displays the org tree with (my) original indent. However, clearly it is not a good solution because you cannot indent/outdent any of the headings. So that hack only works for displaying files.

I took a look at the `org-modern` code but I don't know enough to find a solution. It looks like the function that I might need to tweak to retain the indent is:

```lisp
(defun org-modern--star ()
   ; ... ?
)
```

Apparently, there might be a way to stop `org-modern` from handling the headling stars and rely instead on `org-bullets` to do the beautification, but I couldn't find how to make that work as I still lose the heading indent when `org-modern-mode` is enabled.

Any tips, suggestions or pointers to config options much appreciated ;)

**Comment by bestlem** [comment]
See https://github.com/minad/org-modern/issues/7

**Comment by minad** [comment]
@linuxclef 

> Any tips, suggestions or pointers to config options much appreciated ;)

If you check the customization variables you should find the solution.

**Comment by linuxclef** [comment]
I don't use `org-indent-mode` or `org-modern-indent-mode` and I agree they are not the solution. I couldn't find a standard `org-modern` config setting to do what I want. A bit of digging showed that what I'm after is _something like_ this:

```diff
diff --git a/org-modern.el b/org-modern.el
index 4259918..3323e1e 100644
--- a/org-modern.el
+++ b/org-modern.el
@@ -76,6 +76,10 @@ surrounded with space. For the syntax, refer to `format-time-string'."
   "Prettify tables."
   :type 'boolean)

+(defcustom org-modern-retain-indent nil
+  "Keep org-mode tree structure if true."
+  :type 'boolean)
+
 (defcustom org-modern-table-vertical 3
   "Width of vertical table lines in pixels.
 Set to nil to hide the vertical lines."
@@ -583,7 +587,7 @@ the font.")
    (when (or org-modern-star org-modern-hide-stars)
      `(("^\\(\\**\\)\\(\\*\\) "
         ,@(and (not (eq org-modern-hide-stars t)) org-modern-star '((0 (org-modern--star))))
-        ,@(and (eq org-modern-hide-stars 'leading) '((1 '(face nil invisible t))))
+        ,@(and (not (eq org-modern-retain-indent t)) (eq org-modern-hide-stars 'leading) '((1 '(face nil invisible t))))
         ,@(and (eq org-modern-hide-stars t) '((0 '(face nil invisible t)))))))
    (when org-modern-horizontal-rule
      `(("^[ \t]*-\\{5,\\}$" 0
```

So with an org file like this:

```org
* Test
*** Foo
***** Baz
      Hello, world!
*** Bar
***** Wibble

      Some text.
      More text.
```

... rather than the default display behaviour of `org-modern` that shows the file above as:

```
◉ Test
◈ Foo
✳ Baz
      Hello, world!
◈ Bar
✳ Wibble

      Some text.
      More text.
```

... the diff above lets me see:

```
◉ Test
  ◈ Foo
    ✳ Baz
      Hello, world!
  ◈ Bar
    ✳ Wibble

      Some text.
      More text.
```

I know that diff isn't enough of a fix (as all the other regex's would also need to be adjusted), but would you consider adding an option to allow this sort of behaviour without all the additional complexity of the *indent packages/functions?

**Comment by minad** [comment]
See org-modern-hide-stars

**Comment by linuxclef** [comment]
Oh wow, that's unexpected, but thanks! :smile: Yes, the line below does exactly what I want, but the name and the description of the variable made me think this variable controlled whether the stars were _displayed_, whereas it (also) controls whether the _space_ the stars occupy in the file is retained too:

```lisp
(setq org-modern-hide-stars nil)
```

A quick test shows the behaviour is as follows:

| Value | Default | Leading stars shown | Trailing star shown | Headline indent retained |
|-|-|-|-|-|
| `'leading` | yes | no | yes | no |
| `nil` | no | no | yes | yes |
| `t` | no | no | no | yes |

**Comment by minad** [comment]
> whereas it (also) controls whether the _space_ the stars occupy in the file is retained too when they are displayed

Are you serious? How are the stars supposed to be displayed while not retaining the space they occupy? Is the docstring of the variable so bad or is the name so misleading or didn't you read it? Anyway, I recommend to always investigate all the package  customization variables closely before taking further steps.

**Comment by Inc0n** [comment]
> How are the stars supposed to be displayed while not retaining the space they occupy?

org-superstar-mode does this by allowing user to specify, what the content of the hidestar should be. By default they are 1 empty space for each star. My preference is to use ".". 

Could org-modern potentially support this too?
