### ISSUE TITLE
backslash (`\`) in headers stops styling

### ISSUE THREAD

**Issue by hydrobeam** [minad/org-modern#97]
## Description
Adding a backslash to a file header prevents styling on that line, and also future lines in the file. This styling-prevention doesn't persist for the entire file, since styling resumes.. eventually (I haven't been able to consistently find a point where styling resumes 😅).

Also, modifying a line that's not been styled because of the backslash causes that line to be styled.

## Screenshots/Videos

- unstyled file
![image](https://user-images.githubusercontent.com/70682032/193433695-e9d0580c-0e0d-4210-8f88-f803a351259d.png)
- after removing the line with the backslash and refreshing the buffer 
![image](https://user-images.githubusercontent.com/70682032/193433700-e64e956a-64be-435b-9192-6b39a14b0885.png)

- styling being prevented by a backslash

https://user-images.githubusercontent.com/70682032/193433869-56d2c005-2437-485e-81a6-176484fb0bfc.mp4

- styling resuming when editing a line

https://user-images.githubusercontent.com/70682032/193433880-dce2336e-1d95-4dfc-8ab7-7748046a74bf.mp4

## Config
Here's a pastebin of the file in the screenshots: https://pastebin.com/LnjMKcUB

and here's my config for `org-modern` (if relevant):

```lisp
(use-package! org-modern
  :hook (org-mode . org-modern-mode)
  :config
  (setq org-modern-todo nil)
  (setq org-modern-variable-pitch nil)
  (setq org-modern-todo-faces nil)
  (setq org-modern-checkbox nil)
  (setq org-modern-table nil)
  )
```

**Comment by minad** [comment]
I cannot reproduce this in my setup. Can you create a minimal configuration based on emacs -Q?

**Comment by hydrobeam** [comment]
After some further testing, the issue seemed to have been caused by an unrelated config change to `smartparens`. Sorry for the false report
